//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTTabBarLib.Common
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAPICodePack.Resources.LocalizedMessages", typeof(LocalizedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register application for restart due to bad parameters..
        /// </summary>
        internal static string ApplicationRecoverFailedToRegisterForRestartBadParameters {
            get {
                return ResourceManager.GetString("ApplicationRecoverFailedToRegisterForRestartBadParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application was not registered for recovery due to bad parameters..
        /// </summary>
        internal static string ApplicationRecoveryBadParameters {
            get {
                return ResourceManager.GetString("ApplicationRecoveryBadParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application failed to register for recovery..
        /// </summary>
        internal static string ApplicationRecoveryFailedToRegister {
            get {
                return ResourceManager.GetString("ApplicationRecoveryFailedToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application failed to registered for restart..
        /// </summary>
        internal static string ApplicationRecoveryFailedToRegisterForRestart {
            get {
                return ResourceManager.GetString("ApplicationRecoveryFailedToRegisterForRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister for recovery failed..
        /// </summary>
        internal static string ApplicationRecoveryFailedToUnregister {
            get {
                return ResourceManager.GetString("ApplicationRecoveryFailedToUnregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister for restart failed..
        /// </summary>
        internal static string ApplicationRecoveryFailedToUnregisterForRestart {
            get {
                return ResourceManager.GetString("ApplicationRecoveryFailedToUnregisterForRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method must be called from the registered callback method..
        /// </summary>
        internal static string ApplicationRecoveryMustBeCalledFromCallback {
            get {
                return ResourceManager.GetString("ApplicationRecoveryMustBeCalledFromCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACOnline: {1}{0}Max Charge: {2} mWh{0}Current Charge: {3} mWh{0}Discharge Rate: {4} mWh{0}Estimated Time Remaining: {5}{0}Suggested Critical Battery Charge: {6} mWh{0}Suggested Battery Warning Charge: {7} mWh{0}.
        /// </summary>
        internal static string BatteryStateStringRepresentation {
            get {
                return ResourceManager.GetString("BatteryStateStringRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelable cannot be changed while dialog is showing..
        /// </summary>
        internal static string CancelableCannotBeChanged {
            get {
                return ResourceManager.GetString("CancelableCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog caption cannot be changed while dialog is showing..
        /// </summary>
        internal static string CaptionCannotBeChanged {
            get {
                return ResourceManager.GetString("CaptionCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox text cannot be changed while dialog is showing..
        /// </summary>
        internal static string CheckBoxCannotBeChanged {
            get {
                return ResourceManager.GetString("CheckBoxCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapsed control text cannot be changed while dialog is showing..
        /// </summary>
        internal static string CollapsedTextCannotBeChanged {
            get {
                return ResourceManager.GetString("CollapsedTextCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only supported on Windows 7 or newer..
        /// </summary>
        internal static string CoreHelpersRunningOn7 {
            get {
                return ResourceManager.GetString("CoreHelpersRunningOn7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only supported on Windows Vista or newer..
        /// </summary>
        internal static string CoreHelpersRunningOnVista {
            get {
                return ResourceManager.GetString("CoreHelpersRunningOnVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only supported on Windows XP or newer..
        /// </summary>
        internal static string CoreHelpersRunningOnXp {
            get {
                return ResourceManager.GetString("CoreHelpersRunningOnXp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Button cannot be changed while dialog is showing..
        /// </summary>
        internal static string DefaultButtonCannotBeChanged {
            get {
                return ResourceManager.GetString("DefaultButtonCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog cannot have more than one control with the same name..
        /// </summary>
        internal static string DialogCollectionCannotHaveDuplicateNames {
            get {
                return ResourceManager.GetString("DialogCollectionCannotHaveDuplicateNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog control must be removed from current collections first..
        /// </summary>
        internal static string DialogCollectionControlAlreadyHosted {
            get {
                return ResourceManager.GetString("DialogCollectionControlAlreadyHosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control name cannot be null or zero length..
        /// </summary>
        internal static string DialogCollectionControlNameNull {
            get {
                return ResourceManager.GetString("DialogCollectionControlNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying controls collection while dialog is showing is not supported..
        /// </summary>
        internal static string DialogCollectionModifyShowingDialog {
            get {
                return ResourceManager.GetString("DialogCollectionModifyShowingDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog control name cannot be empty or null..
        /// </summary>
        internal static string DialogControlNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("DialogControlNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog controls cannot be renamed..
        /// </summary>
        internal static string DialogControlsCannotBeRenamed {
            get {
                return ResourceManager.GetString("DialogControlsCannotBeRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string DialogDefaultCaption {
            get {
                return ResourceManager.GetString("DialogDefaultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DialogDefaultContent {
            get {
                return ResourceManager.GetString("DialogDefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DialogDefaultMainInstruction {
            get {
                return ResourceManager.GetString("DialogDefaultMainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded information mode cannot be changed while dialog is showing..
        /// </summary>
        internal static string ExpandedDetailsCannotBeChanged {
            get {
                return ResourceManager.GetString("ExpandedDetailsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded control label cannot be changed while dialog is showing..
        /// </summary>
        internal static string ExpandedLabelCannotBeChanged {
            get {
                return ResourceManager.GetString("ExpandedLabelCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanding state of the dialog cannot be changed while dialog is showing..
        /// </summary>
        internal static string ExpandingStateCannotBeChanged {
            get {
                return ResourceManager.GetString("ExpandingStateCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlinks cannot be enabled/disabled while dialog is showing..
        /// </summary>
        internal static string HyperlinksCannotBetSet {
            get {
                return ResourceManager.GetString("HyperlinksCannotBetSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference path is invalid..
        /// </summary>
        internal static string InvalidReferencePath {
            get {
                return ResourceManager.GetString("InvalidReferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified event handler has not been registered..
        /// </summary>
        internal static string MessageManagerHandlerNotRegistered {
            get {
                return ResourceManager.GetString("MessageManagerHandlerNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred in dialog configuration..
        /// </summary>
        internal static string NativeTaskDialogConfigurationError {
            get {
                return ResourceManager.GetString("NativeTaskDialogConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments to Win32 call..
        /// </summary>
        internal static string NativeTaskDialogInternalErrorArgs {
            get {
                return ResourceManager.GetString("NativeTaskDialogInternalErrorArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog contents too complex..
        /// </summary>
        internal static string NativeTaskDialogInternalErrorComplex {
            get {
                return ResourceManager.GetString("NativeTaskDialogInternalErrorComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected internal error occurred in the Win32 call: {0:x}.
        /// </summary>
        internal static string NativeTaskDialogInternalErrorUnexpected {
            get {
                return ResourceManager.GetString("NativeTaskDialogInternalErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskDialog feature needs to load version 6 of comctl32.dll but a different version is current loaded in memory..
        /// </summary>
        internal static string NativeTaskDialogVersionError {
            get {
                return ResourceManager.GetString("NativeTaskDialogVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog owner cannot be changed while dialog is showing..
        /// </summary>
        internal static string OwnerCannotBeChanged {
            get {
                return ResourceManager.GetString("OwnerCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetThreadExecutionState call failed..
        /// </summary>
        internal static string PowerExecutionStateFailed {
            get {
                return ResourceManager.GetString("PowerExecutionStateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caller had insufficient access rights to get the system battery state..
        /// </summary>
        internal static string PowerInsufficientAccessBatteryState {
            get {
                return ResourceManager.GetString("PowerInsufficientAccessBatteryState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caller had insufficient access rights to get the system power capabilities..
        /// </summary>
        internal static string PowerInsufficientAccessCapabilities {
            get {
                return ResourceManager.GetString("PowerInsufficientAccessCapabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get active power scheme..
        /// </summary>
        internal static string PowerManagerActiveSchemeFailed {
            get {
                return ResourceManager.GetString("PowerManagerActiveSchemeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery is not present on this system..
        /// </summary>
        internal static string PowerManagerBatteryNotPresent {
            get {
                return ResourceManager.GetString("PowerManagerBatteryNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress bar cannot be changed while dialog is showing..
        /// </summary>
        internal static string ProgressBarCannotBeChanged {
            get {
                return ResourceManager.GetString("ProgressBarCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress bar cannot be hosted in multiple dialogs..
        /// </summary>
        internal static string ProgressBarCannotBeHostedInMultipleDialogs {
            get {
                return ResourceManager.GetString("ProgressBarCannotBeHostedInMultipleDialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string PropertyKeyFormatString {
            get {
                return ResourceManager.GetString("PropertyKeyFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize PropVariant..
        /// </summary>
        internal static string PropVariantInitializationError {
            get {
                return ResourceManager.GetString("PropVariantInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-dimensional SafeArrays not supported..
        /// </summary>
        internal static string PropVariantMultiDimArray {
            get {
                return ResourceManager.GetString("PropVariantMultiDimArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String argument cannot be null or empty..
        /// </summary>
        internal static string PropVariantNullString {
            get {
                return ResourceManager.GetString("PropVariantNullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Value type is not supported..
        /// </summary>
        internal static string PropVariantTypeNotSupported {
            get {
                return ResourceManager.GetString("PropVariantTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be cast to unsupported type..
        /// </summary>
        internal static string PropVariantUnsupportedType {
            get {
                return ResourceManager.GetString("PropVariantUnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delegate: {0}, state: {1}, ping: {2}.
        /// </summary>
        internal static string RecoverySettingsFormatString {
            get {
                return ResourceManager.GetString("RecoverySettingsFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to command: {0} restrictions: {1}.
        /// </summary>
        internal static string RestartSettingsFormatString {
            get {
                return ResourceManager.GetString("RestartSettingsFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StandardButtons cannot be changed while dialog is showing..
        /// </summary>
        internal static string StandardButtonsCannotBeChanged {
            get {
                return ResourceManager.GetString("StandardButtonsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup location cannot be changed while dialog is showing..
        /// </summary>
        internal static string StartupLocationCannotBeChanged {
            get {
                return ResourceManager.GetString("StartupLocationCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad button ID in closing event..
        /// </summary>
        internal static string TaskDialogBadButtonId {
            get {
                return ResourceManager.GetString("TaskDialogBadButtonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button text must be non-empty..
        /// </summary>
        internal static string TaskDialogButtonTextEmpty {
            get {
                return ResourceManager.GetString("TaskDialogButtonTextEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check box text must be provided to enable the dialog check box..
        /// </summary>
        internal static string TaskDialogCheckBoxTextRequiredToEnableCheckBox {
            get {
                return ResourceManager.GetString("TaskDialogCheckBoxTextRequiredToEnableCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to close a non-showing dialog..
        /// </summary>
        internal static string TaskDialogCloseNonShowing {
            get {
                return ResourceManager.GetString("TaskDialogCloseNonShowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string TaskDialogDefaultCaption {
            get {
                return ResourceManager.GetString("TaskDialogDefaultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TaskDialogDefaultContent {
            get {
                return ResourceManager.GetString("TaskDialogDefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TaskDialogDefaultMainInstruction {
            get {
                return ResourceManager.GetString("TaskDialogDefaultMainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have more than one default button of a given type..
        /// </summary>
        internal static string TaskDialogOnlyOneDefaultControl {
            get {
                return ResourceManager.GetString("TaskDialogOnlyOneDefaultControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum value provided must be greater than the minimum value..
        /// </summary>
        internal static string TaskDialogProgressBarMaxValueGreaterThanMin {
            get {
                return ResourceManager.GetString("TaskDialogProgressBarMaxValueGreaterThanMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum value provided must be a positive number..
        /// </summary>
        internal static string TaskDialogProgressBarMinValueGreaterThanZero {
            get {
                return ResourceManager.GetString("TaskDialogProgressBarMinValueGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum value provided must less than the maximum value..
        /// </summary>
        internal static string TaskDialogProgressBarMinValueLessThanMax {
            get {
                return ResourceManager.GetString("TaskDialogProgressBarMinValueLessThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value provided must be greater than equal to the minimum value and less than the maximum value..
        /// </summary>
        internal static string TaskDialogProgressBarValueInRange {
            get {
                return ResourceManager.GetString("TaskDialogProgressBarValueInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog cannot display both non-standard buttons and standard buttons..
        /// </summary>
        internal static string TaskDialogSupportedButtonsAndButtons {
            get {
                return ResourceManager.GetString("TaskDialogSupportedButtonsAndButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog cannot display both non-standard buttons and command links..
        /// </summary>
        internal static string TaskDialogSupportedButtonsAndLinks {
            get {
                return ResourceManager.GetString("TaskDialogSupportedButtonsAndLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown dialog control type..
        /// </summary>
        internal static string TaskDialogUnkownControl {
            get {
                return ResourceManager.GetString("TaskDialogUnkownControl", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to AddToMostRecentlyUsedList cannot be changed while dialog is showing..
        /// </summary>
        internal static string AddToMostRecentlyUsedListCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("AddToMostRecentlyUsedListCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AlwaysAppendDefaultExtension cannot be changed while dialog is showing..
        /// </summary>
        internal static string AlwaysAppendDefaultExtensionCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("AlwaysAppendDefaultExtensionCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Index was outside the bounds of the CommonFileDialogComboBox..
        /// </summary>
        internal static string ComboBoxIndexOutsideBounds
        {
            get
            {
                return ResourceManager.GetString("ComboBoxIndexOutsideBounds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File name not available - dialog was canceled..
        /// </summary>
        internal static string CommonFileDialogCanceled
        {
            get
            {
                return ResourceManager.GetString("CommonFileDialogCanceled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shell item could not be created..
        /// </summary>
        internal static string CommonFileDialogCannotCreateShellItem
        {
            get
            {
                return ResourceManager.GetString("CommonFileDialogCannotCreateShellItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Handle provided cannot be IntPtr.Zero..
        /// </summary>
        internal static string CommonFileDialogInvalidHandle
        {
            get
            {
                return ResourceManager.GetString("CommonFileDialogInvalidHandle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple files selected - the FileNames property should be used instead..
        /// </summary>
        internal static string CommonFileDialogMultipleFiles
        {
            get
            {
                return ResourceManager.GetString("CommonFileDialogMultipleFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple files selected - the Items property should be used instead..
        /// </summary>
        internal static string CommonFileDialogMultipleItems
        {
            get
            {
                return ResourceManager.GetString("CommonFileDialogMultipleItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File name not available - dialog has not closed yet..
        /// </summary>
        internal static string CommonFileDialogNotClosed
        {
            get
            {
                return ResourceManager.GetString("CommonFileDialogNotClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Common File Dialog requires Windows Vista or later..
        /// </summary>
        internal static string CommonFileDialogRequiresVista
        {
            get
            {
                return ResourceManager.GetString("CommonFileDialogRequiresVista", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Office Files.
        /// </summary>
        internal static string CommonFiltersOffice
        {
            get
            {
                return ResourceManager.GetString("CommonFiltersOffice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All Picture Files.
        /// </summary>
        internal static string CommonFiltersPicture
        {
            get
            {
                return ResourceManager.GetString("CommonFiltersPicture", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text Files.
        /// </summary>
        internal static string CommonFiltersText
        {
            get
            {
                return ResourceManager.GetString("CommonFiltersText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CreatePrompt cannot be changed while dialog is showing..
        /// </summary>
        internal static string CreatePromptCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("CreatePromptCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Custom controls cannot be removed from a File dialog once added..
        /// </summary>
        internal static string DialogControlCollectionCannotRemoveControls
        {
            get
            {
                return ResourceManager.GetString("DialogControlCollectionCannotRemoveControls", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Control name cannot be null or zero length..
        /// </summary>
        internal static string DialogControlCollectionEmptyName
        {
            get
            {
                return ResourceManager.GetString("DialogControlCollectionEmptyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CommonFileDialogMenuItem controls can only be added to CommonFileDialogMenu controls..
        /// </summary>
        internal static string DialogControlCollectionMenuItemControlsCannotBeAdded
        {
            get
            {
                return ResourceManager.GetString("DialogControlCollectionMenuItemControlsCannotBeAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modifying controls collection while dialog is showing is not supported..
        /// </summary>
        internal static string DialogControlCollectionModifyingControls
        {
            get
            {
                return ResourceManager.GetString("DialogControlCollectionModifyingControls", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog cannot have more than one control with the same name..
        /// </summary>
        internal static string DialogControlCollectionMoreThanOneControl
        {
            get
            {
                return ResourceManager.GetString("DialogControlCollectionMoreThanOneControl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog control must be removed from current collections first..
        /// </summary>
        internal static string DialogControlCollectionRemoveControlFirst
        {
            get
            {
                return ResourceManager.GetString("DialogControlCollectionRemoveControlFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EnsureFileExists cannot be changed while dialog is showing..
        /// </summary>
        internal static string EnsureFileExistsCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("EnsureFileExistsCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EnsurePathExists cannot be changed while dialog is showing..
        /// </summary>
        internal static string EnsurePathExistsCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("EnsurePathExistsCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EnsureReadOnly cannot be changed while dialog is showing..
        /// </summary>
        internal static string EnsureReadonlyCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("EnsureReadonlyCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EnsureValidNames cannot be changed while dialog is showing..
        /// </summary>
        internal static string EnsureValidNamesCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("EnsureValidNamesCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browsing to object failed..
        /// </summary>
        internal static string ExplorerBrowserBrowseToObjectFailed
        {
            get
            {
                return ResourceManager.GetString("ExplorerBrowserBrowseToObjectFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ExplorerBrowser failed to get current view..
        /// </summary>
        internal static string ExplorerBrowserFailedToGetView
        {
            get
            {
                return ResourceManager.GetString("ExplorerBrowserFailedToGetView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to get icon size..
        /// </summary>
        internal static string ExplorerBrowserIconSize
        {
            get
            {
                return ResourceManager.GetString("ExplorerBrowserIconSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected error retrieving item count..
        /// </summary>
        internal static string ExplorerBrowserItemCount
        {
            get
            {
                return ResourceManager.GetString("ExplorerBrowserItemCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected error retrieving selected item count..
        /// </summary>
        internal static string ExplorerBrowserSelectedItemCount
        {
            get
            {
                return ResourceManager.GetString("ExplorerBrowserSelectedItemCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected error retrieving selection..
        /// </summary>
        internal static string ExplorerBrowserUnexpectedError
        {
            get
            {
                return ResourceManager.GetString("ExplorerBrowserUnexpectedError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected error retrieving view items..
        /// </summary>
        internal static string ExplorerBrowserViewItems
        {
            get
            {
                return ResourceManager.GetString("ExplorerBrowserViewItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The given path does not exist ({0}).
        /// </summary>
        internal static string FilePathNotExist
        {
            get
            {
                return ResourceManager.GetString("FilePathNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Guid does not identify a known folder..
        /// </summary>
        internal static string FolderIdsUnknownGuid
        {
            get
            {
                return ResourceManager.GetString("FolderIdsUnknownGuid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ControlPanel Category.
        /// </summary>
        internal static string FolderTypeCategory
        {
            get
            {
                return ResourceManager.GetString("FolderTypeCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ControlPanel Classic.
        /// </summary>
        internal static string FolderTypeClassic
        {
            get
            {
                return ResourceManager.GetString("FolderTypeClassic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Communications.
        /// </summary>
        internal static string FolderTypeCommunications
        {
            get
            {
                return ResourceManager.GetString("FolderTypeCommunications", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compressed Folder.
        /// </summary>
        internal static string FolderTypeCompressedFolder
        {
            get
            {
                return ResourceManager.GetString("FolderTypeCompressedFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string FolderTypeContacts
        {
            get
            {
                return ResourceManager.GetString("FolderTypeContacts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string FolderTypeDocuments
        {
            get
            {
                return ResourceManager.GetString("FolderTypeDocuments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string FolderTypeGames
        {
            get
            {
                return ResourceManager.GetString("FolderTypeGames", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generic Library.
        /// </summary>
        internal static string FolderTypeGenericLibrary
        {
            get
            {
                return ResourceManager.GetString("FolderTypeGenericLibrary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string FolderTypeInvalid
        {
            get
            {
                return ResourceManager.GetString("FolderTypeInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string FolderTypeLibrary
        {
            get
            {
                return ResourceManager.GetString("FolderTypeLibrary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string FolderTypeMusic
        {
            get
            {
                return ResourceManager.GetString("FolderTypeMusic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Music Icons.
        /// </summary>
        internal static string FolderTypeMusicIcons
        {
            get
            {
                return ResourceManager.GetString("FolderTypeMusicIcons", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network Explorer.
        /// </summary>
        internal static string FolderTypeNetworkExplorer
        {
            get
            {
                return ResourceManager.GetString("FolderTypeNetworkExplorer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not Specified.
        /// </summary>
        internal static string FolderTypeNotSpecified
        {
            get
            {
                return ResourceManager.GetString("FolderTypeNotSpecified", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Search.
        /// </summary>
        internal static string FolderTypeOpenSearch
        {
            get
            {
                return ResourceManager.GetString("FolderTypeOpenSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other Users.
        /// </summary>
        internal static string FolderTypeOtherUsers
        {
            get
            {
                return ResourceManager.GetString("FolderTypeOtherUsers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        internal static string FolderTypePictures
        {
            get
            {
                return ResourceManager.GetString("FolderTypePictures", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Printers.
        /// </summary>
        internal static string FolderTypePrinters
        {
            get
            {
                return ResourceManager.GetString("FolderTypePrinters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RecordedTV.
        /// </summary>
        internal static string FolderTypeRecordedTV
        {
            get
            {
                return ResourceManager.GetString("FolderTypeRecordedTV", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RecycleBin.
        /// </summary>
        internal static string FolderTypeRecycleBin
        {
            get
            {
                return ResourceManager.GetString("FolderTypeRecycleBin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saved Games.
        /// </summary>
        internal static string FolderTypeSavedGames
        {
            get
            {
                return ResourceManager.GetString("FolderTypeSavedGames", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search Connector.
        /// </summary>
        internal static string FolderTypeSearchConnector
        {
            get
            {
                return ResourceManager.GetString("FolderTypeSearchConnector", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Searches.
        /// </summary>
        internal static string FolderTypeSearches
        {
            get
            {
                return ResourceManager.GetString("FolderTypeSearches", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generic SearchResults.
        /// </summary>
        internal static string FolderTypeSearchResults
        {
            get
            {
                return ResourceManager.GetString("FolderTypeSearchResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Software Explorer.
        /// </summary>
        internal static string FolderTypeSoftwareExplorer
        {
            get
            {
                return ResourceManager.GetString("FolderTypeSoftwareExplorer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User Files.
        /// </summary>
        internal static string FolderTypeUserFiles
        {
            get
            {
                return ResourceManager.GetString("FolderTypeUserFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Users Libraries.
        /// </summary>
        internal static string FolderTypeUserLibraries
        {
            get
            {
                return ResourceManager.GetString("FolderTypeUserLibraries", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string FolderTypeVideos
        {
            get
            {
                return ResourceManager.GetString("FolderTypeVideos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IsExpandedMode cannot be changed while dialog is showing..
        /// </summary>
        internal static string IsExpandedModeCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("IsExpandedModeCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Custom categories cannot be added while recent documents tracking is turned off..
        /// </summary>
        internal static string JumpListCustomCategoriesDisabled
        {
            get
            {
                return ResourceManager.GetString("JumpListCustomCategoriesDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file type is not registered with this application..
        /// </summary>
        internal static string JumpListFileTypeNotRegistered
        {
            get
            {
                return ResourceManager.GetString("JumpListFileTypeNotRegistered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JumpListLink&apos;s path is required and cannot be null..
        /// </summary>
        internal static string JumpListLinkPathRequired
        {
            get
            {
                return ResourceManager.GetString("JumpListLinkPathRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JumpListLink&apos;s title is required and cannot be null..
        /// </summary>
        internal static string JumpListLinkTitleRequired
        {
            get
            {
                return ResourceManager.GetString("JumpListLinkTitleRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Negative numbers are not allowed for the ordinal position..
        /// </summary>
        internal static string JumpListNegativeOrdinalPosition
        {
            get
            {
                return ResourceManager.GetString("JumpListNegativeOrdinalPosition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given Known Folder ID is invalid..
        /// </summary>
        internal static string KnownFolderInvalidGuid
        {
            get
            {
                return ResourceManager.GetString("KnownFolderInvalidGuid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parsing name is invalid..
        /// </summary>
        internal static string KnownFolderParsingName
        {
            get
            {
                return ResourceManager.GetString("KnownFolderParsingName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creation of window has failed, view inner exception for details..
        /// </summary>
        internal static string MessageListenerCannotCreateWindow
        {
            get
            {
                return ResourceManager.GetString("MessageListenerCannotCreateWindow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Window class could not be registered, check inner exception for more details..
        /// </summary>
        internal static string MessageListenerClassNotRegistered
        {
            get
            {
                return ResourceManager.GetString("MessageListenerClassNotRegistered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message filter registration failed..
        /// </summary>
        internal static string MessageListenerFilterUnableToRegister
        {
            get
            {
                return ResourceManager.GetString("MessageListenerFilterUnableToRegister", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No listener handled of that value is registered..
        /// </summary>
        internal static string MessageListenerFilterUnknownListenerHandle
        {
            get
            {
                return ResourceManager.GetString("MessageListenerFilterUnknownListenerHandle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot create window on the listener thread because there is no existing window on the listener thread..
        /// </summary>
        internal static string MessageListenerNoWindowHandle
        {
            get
            {
                return ResourceManager.GetString("MessageListenerNoWindowHandle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NavigateToShortcut cannot be changed while dialog is showing..
        /// </summary>
        internal static string NavigateToShortcutCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("NavigateToShortcutCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parent cannot be null..
        /// </summary>
        internal static string NavigationLogNullParent
        {
            get
            {
                return ResourceManager.GetString("NavigationLogNullParent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The method or operation is not implemented..
        /// </summary>
        internal static string NotImplementedException
        {
            get
            {
                return ResourceManager.GetString("NotImplementedException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OverwritePrompt cannot be changed while dialog is showing..
        /// </summary>
        internal static string OverwritePromptCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("OverwritePromptCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This CanonicalName is not a valid index..
        /// </summary>
        internal static string PropertyCollectionCanonicalInvalidIndex
        {
            get
            {
                return ResourceManager.GetString("PropertyCollectionCanonicalInvalidIndex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This PropertyKey is not a valid index..
        /// </summary>
        internal static string PropertyCollectionInvalidIndex
        {
            get
            {
                return ResourceManager.GetString("PropertyCollectionInvalidIndex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Argument CanonicalName cannot be null or empty..
        /// </summary>
        internal static string PropertyCollectionNullCanonicalName
        {
            get
            {
                return ResourceManager.GetString("PropertyCollectionNullCanonicalName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Index was outside the bounds of the CommonFileDialogRadioButtonList..
        /// </summary>
        internal static string RadioButtonListIndexOutOfBounds
        {
            get
            {
                return ResourceManager.GetString("RadioButtonListIndexOutOfBounds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RestoreDirectory cannot be changed while dialog is showing..
        /// </summary>
        internal static string RestoreDirectoryCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("RestoreDirectoryCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieved a null shell item from dialog..
        /// </summary>
        internal static string SaveFileNullItem
        {
            get
            {
                return ResourceManager.GetString("SaveFileNullItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given property key is invalid..
        /// </summary>
        internal static string SearchConditionFactoryInvalidProperty
        {
            get
            {
                return ResourceManager.GetString("SearchConditionFactoryInvalidProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shell Exception has occurred, look at inner exception for information..
        /// </summary>
        internal static string ShellExceptionDefaultText
        {
            get
            {
                return ResourceManager.GetString("ShellExceptionDefaultText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GetParsingName has failed..
        /// </summary>
        internal static string ShellHelperGetParsingNameFailed
        {
            get
            {
                return ResourceManager.GetString("ShellHelperGetParsingNameFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The given CanonicalName is not valid..
        /// </summary>
        internal static string ShellInvalidCanonicalName
        {
            get
            {
                return ResourceManager.GetString("ShellInvalidCanonicalName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DefaultSaveFolder path not found..
        /// </summary>
        internal static string ShellLibraryDefaultSaveFolderNotFound
        {
            get
            {
                return ResourceManager.GetString("ShellLibraryDefaultSaveFolderNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LibraryName cannot be empty..
        /// </summary>
        internal static string ShellLibraryEmptyName
        {
            get
            {
                return ResourceManager.GetString("ShellLibraryEmptyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Folder path not found..
        /// </summary>
        internal static string ShellLibraryFolderNotFound
        {
            get
            {
                return ResourceManager.GetString("ShellLibraryFolderNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid FolderType Guid..
        /// </summary>
        internal static string ShellLibraryInvalidFolderType
        {
            get
            {
                return ResourceManager.GetString("ShellLibraryInvalidFolderType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The given known folder is not a valid library..
        /// </summary>
        internal static string ShellLibraryInvalidLibrary
        {
            get
            {
                return ResourceManager.GetString("ShellLibraryInvalidLibrary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get the display name..
        /// </summary>
        internal static string ShellObjectCannotGetDisplayName
        {
            get
            {
                return ResourceManager.GetString("ShellObjectCannotGetDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Destination array too small, or invalid arrayIndex..
        /// </summary>
        internal static string ShellObjectCollectionArrayTooSmall
        {
            get
            {
                return ResourceManager.GetString("ShellObjectCollectionArrayTooSmall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Must have at least one shell object in the collection..
        /// </summary>
        internal static string ShellObjectCollectionEmptyCollection
        {
            get
            {
                return ResourceManager.GetString("ShellObjectCollectionEmptyCollection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot insert items into a read only list..
        /// </summary>
        internal static string ShellObjectCollectionInsertReadOnly
        {
            get
            {
                return ResourceManager.GetString("ShellObjectCollectionInsertReadOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot remove items from a read only list..
        /// </summary>
        internal static string ShellObjectCollectionRemoveReadOnly
        {
            get
            {
                return ResourceManager.GetString("ShellObjectCollectionRemoveReadOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shell item could not be created..
        /// </summary>
        internal static string ShellObjectCreationFailed
        {
            get
            {
                return ResourceManager.GetString("ShellObjectCreationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shell Object creation requires Windows Vista or higher operating system..
        /// </summary>
        internal static string ShellObjectFactoryPlatformNotSupported
        {
            get
            {
                return ResourceManager.GetString("ShellObjectFactoryPlatformNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to Create Shell Item..
        /// </summary>
        internal static string ShellObjectFactoryUnableToCreateItem
        {
            get
            {
                return ResourceManager.GetString("ShellObjectFactoryUnableToCreateItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration for change notification has failed..
        /// </summary>
        internal static string ShellObjectWatcherRegisterFailed
        {
            get
            {
                return ResourceManager.GetString("ShellObjectWatcherRegisterFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to change watched events while listening..
        /// </summary>
        internal static string ShellObjectWatcherUnableToChangeEvents
        {
            get
            {
                return ResourceManager.GetString("ShellObjectWatcherUnableToChangeEvents", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value on this property cannot be set. To set the property value, use the ShellObject that is associated with this property..
        /// </summary>
        internal static string ShellPropertyCannotSetProperty
        {
            get
            {
                return ResourceManager.GetString("ShellPropertyCannotSetProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No constructor found matching requested argument types..
        /// </summary>
        internal static string ShellPropertyFactoryConstructorNotFound
        {
            get
            {
                return ResourceManager.GetString("ShellPropertyFactoryConstructorNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to set property..
        /// </summary>
        internal static string ShellPropertySetValue
        {
            get
            {
                return ResourceManager.GetString("ShellPropertySetValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to get writable property store for this property..
        /// </summary>
        internal static string ShellPropertyUnableToGetWritableProperty
        {
            get
            {
                return ResourceManager.GetString("ShellPropertyUnableToGetWritableProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A value had to be truncated in a string or rounded if a numeric value. Set AllowTruncatedValue to true to prevent this exception..
        /// </summary>
        internal static string ShellPropertyValueTruncated
        {
            get
            {
                return ResourceManager.GetString("ShellPropertyValueTruncated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This Property is available on Windows 7 only..
        /// </summary>
        internal static string ShellPropertyWindows7
        {
            get
            {
                return ResourceManager.GetString("ShellPropertyWindows7", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This property only accepts a value of type \&quot;{0}\&quot;..
        /// </summary>
        internal static string ShellPropertyWrongType
        {
            get
            {
                return ResourceManager.GetString("ShellPropertyWrongType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to set list of sort columns..
        /// </summary>
        internal static string ShellSearchFolderUnableToSetSortColumns
        {
            get
            {
                return ResourceManager.GetString("ShellSearchFolderUnableToSetSortColumns", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to set visible columns..
        /// </summary>
        internal static string ShellSearchFolderUnableToSetVisibleColumns
        {
            get
            {
                return ResourceManager.GetString("ShellSearchFolderUnableToSetVisibleColumns", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CurrentSize (width or height) cannot be greater than the maximum size: {0}..
        /// </summary>
        internal static string ShellThumbnailCurrentSizeRange
        {
            get
            {
                return ResourceManager.GetString("ShellThumbnailCurrentSizeRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The current ShellObject does not have a thumbnail. Try using ShellThumbnailFormatOption.Default to get the icon for this item..
        /// </summary>
        internal static string ShellThumbnailDoesNotHaveThumbnail
        {
            get
            {
                return ResourceManager.GetString("ShellThumbnailDoesNotHaveThumbnail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The current ShellObject does not have a valid thumbnail handler or there was a problem in extracting the thumbnail for this specific shell object..
        /// </summary>
        internal static string ShellThumbnailNoHandler
        {
            get
            {
                return ResourceManager.GetString("ShellThumbnailNoHandler", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CurrentSize (width or height) cannot be 0..
        /// </summary>
        internal static string ShellThumbnailSizeCannotBe0
        {
            get
            {
                return ResourceManager.GetString("ShellThumbnailSizeCannotBe0", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ShowHiddenItems cannot be changed while dialog is showing..
        /// </summary>
        internal static string ShowHiddenItemsCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("ShowHiddenItemsCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show places list cannot be changed while dialog is showing..
        /// </summary>
        internal static string ShowPlacesListCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("ShowPlacesListCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Stock Icon identifier given is invalid ({0})..
        /// </summary>
        internal static string StockIconInvalidGuid
        {
            get
            {
                return ResourceManager.GetString("StockIconInvalidGuid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Child control&apos;s window handle cannot be zero..
        /// </summary>
        internal static string TabbedThumbnailZeroChildHandle
        {
            get
            {
                return ResourceManager.GetString("TabbedThumbnailZeroChildHandle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parent window handle cannot be zero..
        /// </summary>
        internal static string TabbedThumbnailZeroParentHandle
        {
            get
            {
                return ResourceManager.GetString("TabbedThumbnailZeroParentHandle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TabbedThumbnailProxyWindow has not been set..
        /// </summary>
        internal static string TasbarWindowProxyWindowSet
        {
            get
            {
                return ResourceManager.GetString("TasbarWindowProxyWindowSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A valid active Window is needed to update the Taskbar..
        /// </summary>
        internal static string TaskbarManagerValidWindowRequired
        {
            get
            {
                return ResourceManager.GetString("TaskbarManagerValidWindowRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The array of buttons must contain at least 1 item..
        /// </summary>
        internal static string TaskbarWindowEmptyButtonArray
        {
            get
            {
                return ResourceManager.GetString("TaskbarWindowEmptyButtonArray", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tool bar buttons for this window are already added. Please refer to the Remarks section of the AddButtons method for more information on updating the properties or hiding existing buttons..
        /// </summary>
        internal static string TaskbarWindowManagerButtonsAlreadyAdded
        {
            get
            {
                return ResourceManager.GetString("TaskbarWindowManagerButtonsAlreadyAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value is already set. It cannot be set more than once..
        /// </summary>
        internal static string TaskbarWindowValueSet
        {
            get
            {
                return ResourceManager.GetString("TaskbarWindowValueSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The given control has not been added to the taskbar..
        /// </summary>
        internal static string ThumbnailManagerControlNotAdded
        {
            get
            {
                return ResourceManager.GetString("ThumbnailManagerControlNotAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Window handle is invalid..
        /// </summary>
        internal static string ThumbnailManagerInvalidHandle
        {
            get
            {
                return ResourceManager.GetString("ThumbnailManagerInvalidHandle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This preview has already been added..
        /// </summary>
        internal static string ThumbnailManagerPreviewAdded
        {
            get
            {
                return ResourceManager.GetString("ThumbnailManagerPreviewAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The given preview has not been added to the taskbar..
        /// </summary>
        internal static string ThumbnailManagerPreviewNotAdded
        {
            get
            {
                return ResourceManager.GetString("ThumbnailManagerPreviewNotAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum number of buttons allowed is 7..
        /// </summary>
        internal static string ThumbnailToolbarManagerMaxButtons
        {
            get
            {
                return ResourceManager.GetString("ThumbnailToolbarManagerMaxButtons", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Null or empty arrays are not allowed..
        /// </summary>
        internal static string ThumbnailToolbarManagerNullEmptyArray
        {
            get
            {
                return ResourceManager.GetString("ThumbnailToolbarManagerNullEmptyArray", resourceCulture);
            }
        }



    }
}
