//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizoPlugins {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuizoPlugins.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap CopyButton_large {
            get {
                object obj = ResourceManager.GetObject("CopyButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CopyButton_small {
            get {
                object obj = ResourceManager.GetObject("CopyButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CopyToButton_large {
            get {
                object obj = ResourceManager.GetObject("CopyToButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CopyToButton_small {
            get {
                object obj = ResourceManager.GetObject("CopyToButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CutButton_large {
            get {
                object obj = ResourceManager.GetObject("CutButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CutButton_small {
            get {
                object obj = ResourceManager.GetObject("CutButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeleteButton_large {
            get {
                object obj = ResourceManager.GetObject("DeleteButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeleteButton_small {
            get {
                object obj = ResourceManager.GetObject("DeleteButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MoveToButton_large {
            get {
                object obj = ResourceManager.GetObject("MoveToButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MoveToButton_small {
            get {
                object obj = ResourceManager.GetObject("MoveToButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PasteButton_large {
            get {
                object obj = ResourceManager.GetObject("PasteButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PasteButton_small {
            get {
                object obj = ResourceManager.GetObject("PasteButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PropertiesButton_large {
            get {
                object obj = ResourceManager.GetObject("PropertiesButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PropertiesButton_small {
            get {
                object obj = ResourceManager.GetObject("PropertiesButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedoButton_large {
            get {
                object obj = ResourceManager.GetObject("RedoButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedoButton_small {
            get {
                object obj = ResourceManager.GetObject("RedoButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SendToParentButton_large {
            get {
                object obj = ResourceManager.GetObject("SendToParentButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SendToParentButton_small {
            get {
                object obj = ResourceManager.GetObject("SendToParentButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut;Copy;Paste;Delete;Copy To Folder;Move To Folder;Undo;Send To Parent;Properties.
        /// </summary>
        internal static string str {
            get {
                return ResourceManager.GetString("str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切り取り;コピー;貼り付け;削除;フォルダへコピー;フォルダへ移動;元に戻す;一階層上へ送る;プロパティ.
        /// </summary>
        internal static string str_ja {
            get {
                return ResourceManager.GetString("str_ja", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap UndoButton_large {
            get {
                object obj = ResourceManager.GetObject("UndoButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UndoButton_small {
            get {
                object obj = ResourceManager.GetObject("UndoButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
