//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTTabBarLib {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_String_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_String_de_DE() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QTTabBarLib.Resources_String_de_DE", typeof(Resources_String_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Trennzeichen;Zurückgehen;Vorwärtsgehen;Gruppen;Kürzlich geschlossen;Anwendungen;Neues Fenster;Dies klonen;Sperren;Kopierwerkzeug;Oberste;Schließen;Alles außer dem aktuellen schließen;Fenster schließen;Links schließen;Rechts schließen;Eine Ebene höher;Neu laden;Suchen;Deckkraft;Suchfeld;Optionen 的本地化字符串。
        /// </summary>
        public static string ButtonBar_BtnName {
            get {
                return ResourceManager.GetString("ButtonBar_BtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pfad;Name;Aktueller Ordnerpfad;Aktueller Ordnername;MD5; Elemente;Pfade aller geöffneten Registerkarten 的本地化字符串。
        /// </summary>
        public static string ButtonBar_Misc {
            get {
                return ResourceManager.GetString("ButtonBar_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Liste;Details;Kacheln;Standard 的本地化字符串。
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK;Abbrechen;&amp;Übernehmen;&amp;Standard;Zurücksetzen &amp;Seite;&amp;Alles Zurücksetzen;Zurücksetzen;Hinzufügen;Hinzufügen...;Entfernen;Optionen;Aktivieren;Deaktivieren;Rückgängig;Laden...;Speichern... 的本地化字符串。
        /// </summary>
        public static string DialogButtons {
            get {
                return ResourceManager.GetString("DialogButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kopieren nach:;Verschieben nach:;Verknüpfung erstellen in: 的本地化字符串。
        /// </summary>
        public static string DragDropToolTip {
            get {
                return ResourceManager.GetString("DragDropToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation fehlgeschlagen.\r\nBitte stellen Sie sicher, dass die Datei oder das Ziel der Verknüpfung existiert:\r\n\r\n{0};Fehler - QTTabBar;Warnung:  Die QTTabBar konnte nicht automatisch aktiviert werden. Um sie manuell zu aktivieren, drücken Sie die Alt-Taste, lassen Sie sie los und wählen Sie QTTabBar aus dem Menü Ansicht/Symbolleisten.;Konnte nicht aktiviert werden;Fehler;QTTabBar-Hook-Bibliothek konnte nicht geladen werden.;QTTabBar-Hook-Bibliothek konnte nicht initialisiert werden.;Einige Funktionen s [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ErrorDialogs {
            get {
                return ResourceManager.GetString("ErrorDialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bilddateien;Sprachdateien;Plugin-Dateien 的本地化字符串。
        /// </summary>
        public static string FileFilters {
            get {
                return ResourceManager.GetString("FileFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pfad;Hash;Schließen;Löschen;Aktualisieren;Immer im Vordergrund;Ergebnis anzeigen;Löschen beim Schließen;Vollständiger Pfad;(Jetzt berechnen...) 的本地化字符串。
        /// </summary>
        public static string FileHashComputer {
            get {
                return ResourceManager.GetString("FileHashComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alle;Links;Oben;Rechts;Unten 的本地化字符串。
        /// </summary>
        public static string MarginDropDown {
            get {
                return ResourceManager.GetString("MarginDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desktop Suche;Bilddatei ist ungültig.\r\n\r\nBitte geben Sie eine 432 x 40 px große Bilddatei an.;Suchergebnisse in;Verknüpfung;Wählen Sie Ihre Datei;Wählen Sie Ihren Ordner;Experimentell;Dummy 的本地化字符串。
        /// </summary>
        public static string Misc_Strings {
            get {
                return ResourceManager.GetString("Misc_Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ändern Sie das Verhalten von Explorer-Fenstern; Einzelfenstermodus; Erfassen neuer Explorer-Fenster als neue Registerkarten; Neue Explorer-Fenster nicht erfassen; Standardspeicherort für neue Fenster und Registerkarten; Sitzungsspeicherung; Starten Sie jedes Mal eine neue Sitzung; Wiederherstellen aller Registerkarten aus der vorherigen Sitzung; Wiederherstellen nur der gesperrten Registerkarten aus der vorherigen Sitzung; Wenn die Schließen-Schaltfläche angeklickt wird; Schließen Sie das Fenster; Schließen [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Options_Page01_Window {
            get {
                return ResourceManager.GetString("Options_Page01_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ändern Sie die Optionen für die Registerkarten. Neue Registerkarten öffnen:;Wenn die aktuelle Registerkarte geschlossen wird, wechseln Sie zu der Registerkarte: ;Sofort zu neuen Tabs wechseln;Vorhandene Tabs wiederverwenden;Mehrdeutige Tabs umbenennen;Beim Ziehen über einen Tab zu diesem wechseln;Menü Unterordner-Inhalt anzeigen;Tab-Symbole;Ordnersymbole auf Tabs anzeigen;Menü Unterordner-Inhalt anzeigen, wenn auf das Symbol geklickt wird;Laufwerksbuchstabe auf dem Symbol anzeigen;Schließen-Schaltfläche;Sch [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Options_Page02_Tabs {
            get {
                return ResourceManager.GetString("Options_Page02_Tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aktivieren oder Deaktivieren von Tweaks für die Listenansicht des Explorers. Tweaks, die mit beiden Listenansichten verwendet werden können; Anzeige von Spaltenüberschriften in allen Ansichtsmodi (Windows Vista/7); Verwendung der Standard-Dateisystemansicht für Bibliotheksordner (Windows 7); Abwählen der Dateierweiterung beim Umbenennen von Dateien (Windows XP); Auswahl mit F2 beim Umbenennen umschalten; Umdrehen beim Verschieben der Auswahl mit den Pfeiltasten; Rücktaste geht eine Ebene nach oben (Windows  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Options_Page03_Tweaks {
            get {
                return ResourceManager.GetString("Options_Page03_Tweaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ändern Sie das Verhalten von Unterordner- und Vorschau-Tooltips;Unterordner-Inhalte;Unterordner-Inhalte aktivieren;Nur bei gedrückter Umschalttaste;Dateien anzeigen;Vorschau-Tooltips anzeigen, wenn Sie mit der Maus über Menüpunkte fahren;Vorschau-Tooltips;Vorschau-Tooltips aktivieren;Nur bei gedrückter Umschalttaste;Dateiinformationen unter Bildern anzeigen;Maximale Breite x Höhe:;Schriftart:;Textdateitypen;Bild- und Videodateitypen 的本地化字符串。
        /// </summary>
        public static string Options_Page04_Tooltips {
            get {
                return ResourceManager.GetString("Options_Page04_Tooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allgemeine Einstellungen für das Verhalten von QTTabBar;Taskleisten-Integration;Registerkartenvorschau in der Taskleiste anzeigen;Verlauf;Verlauf geschlossener Registerkarten behalten;Jetzt löschen;Verlauf geöffneter Dateien behalten;Netzwerk;Netzwerk-Timeout (geben Sie 0 für die Systemvorgabe ein):;Regelmäßig nach Updates suchen;Jetzt prüfen;Exportieren;Einstellungen exportieren...;Dateiverlauf löschen?;Registerkartenverlauf löschen? 的本地化字符串。
        /// </summary>
        public static string Options_Page05_General {
            get {
                return ResourceManager.GetString("Options_Page05_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ändern Sie das Aussehen von Registerkarten oder der Registerkartenleiste. Registerkartenbild;Benutzerdefiniertes Registerkartenbild verwenden:;Größenränder:;Überlappungsbereich:;Inhaltsränder:;Transparente Bereiche testen;Registerkartengröße;Höhe:;Minimale Breite:;Maximale Breite:;Größenmodus:;Volle Breite;Gleiche Größe;Registerkartentext;Textfarben:;Schattenfarben:;Aktive Farbe;Inaktive Farbe;Mouseover-Farbe;Textschrift:;Ausrichtung:;Links;Zentriert;Symbolleistenhintergrund;Bild;Volltonfarbe;Bild für jede  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Options_Page06_Appearance {
            get {
                return ResourceManager.GetString("Options_Page06_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weisen Sie verschiedenen Mausaktionen Befehle zu;Um eine Mausbindung hinzuzufügen, führen Sie eine Mausaktion auf dem Plus-Symbol links neben dem entsprechenden Zieltyp aus.  Um eine Bindung zu entfernen, markieren Sie sie in der Liste und drücken Sie die Entf-Taste.;Weitere Mausoptionen;Mausrad rollt das Fenster unter der Maus;Mausakkord;Aktion;Überall;Tabulator;Tab-Leisten-Hintergrund;Ordner-Link;Datei oder Ordner;Explorer-Hintergrund;Linksklick;Rechtsklick;Mittelklick;Doppelklick;X1-Klick;X2-Klick;Diese  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Options_Page07_Mouse {
            get {
                return ResourceManager.GetString("Options_Page07_Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tastenkombinationen ändern;Wählen Sie eine Aktion aus der Liste aus und drücken Sie die Tastenkombination, die Sie damit verbinden möchten.  Drücken Sie Escape, um die Bindung zu löschen.;Andere Tastaturoptionen;Tabulatorwechsel-Fenster anzeigen, wenn Strg + Tab gedrückt wird;Aktion;Tastendruck;Diese Taste ist bereits zugewiesen an:;Soll sie neu zugewiesen werden?;Tastenkonflikt 的本地化字符串。
        /// </summary>
        public static string Options_Page08_Keys {
            get {
                return ResourceManager.GetString("Options_Page08_Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Erstellen und Verwalten von Registerkartengruppen;Um einer Gruppe ein Tastenkürzel zuzuweisen, wählen Sie sie aus und drücken Sie die entsprechende Tastengeste.  Drücken Sie Escape, um die Bindung zu löschen.;Neue Gruppe erstellen;Ordner;Start;Tastenkürzel;Neue Gruppe;Gruppe &quot;{0}&quot; öffnen 的本地化字符串。
        /// </summary>
        public static string Options_Page09_Groups {
            get {
                return ResourceManager.GetString("Options_Page09_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Erstellen Sie Verknüpfungen zu häufig verwendeten Dateien oder Anwendungen.;Um einer Anwendung eine Verknüpfung zuzuweisen, wählen Sie sie aus und drücken Sie die entsprechende Tastenkombination.  Drücken Sie Escape, um die Verknüpfung zu löschen.;Neuen Ordner erstellen;Pfad:;Argumente:;Arbeitsverzeichnis:;Anwendung;Verknüpfungstaste;Die folgenden Schlüsselwörter werden zur Laufzeit durch Pfadangaben in doppelten Anführungszeichen ersetzt.;Ausgewählte Dateien.;Ausgewählte Ordner.;Ausgewählte Dateien und Ord [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Options_Page10_Apps {
            get {
                return ResourceManager.GetString("Options_Page10_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anpassen der Schaltflächenleiste;Schaltflächen;Optionen für die Schaltflächenleiste;Große Symbole;Beschriftungen auf Schaltflächen anzeigen;Reihenfolge der Dropdown-Schaltflächenmenüs festlegen;Größe des Suchfelds festlegen;Benutzerdefinierte Schaltflächen-Icons 的本地化字符串。
        /// </summary>
        public static string Options_Page11_ButtonBar {
            get {
                return ResourceManager.GetString("Options_Page11_ButtonBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugins von Drittanbietern verwalten.;Plugin installieren;(Deaktiviert);von {0};{0} wurde entfernt.;Dieses Plugin wird installiert, wenn Sie auf OK oder Übernehmen drücken.;Dieses Plugin wird aktiviert, wenn Sie auf OK oder Übernehmen drücken.;Dieses Plugin wird deaktiviert, wenn Sie auf OK oder Übernehmen drücken.;Die Deinstallation dieses Plugins deinstalliert auch die folgenden Plugins:;Fortfahren?;Aktivieren;Deaktivieren 的本地化字符串。
        /// </summary>
        public static string Options_Page12_Plugins {
            get {
                return ResourceManager.GetString("Options_Page12_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sprache ändern;Hauptsprache;Eingebaute Sprache verwenden:;Sprachdatei verwenden:;Plugin-Sprachdateien;Sprachdatei-Editor;Spracheditor anzeigen...;Original;Übersetzt;Alle Einträge auf ihren ursprünglichen Wert zurücksetzen?;Fehler beim Speichern der Datei.;简体中文;English;German 的本地化字符串。
        /// </summary>
        public static string Options_Page13_Language {
            get {
                return ResourceManager.GetString("Options_Page13_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Credits und Versionsinformationen anzeigen:;Originalcode von {0};Hauptentwickler:;Andere Entwickler:;Symbole und Grafiken:;Wenn Sie QTTabBar nützlich finden, ziehen Sie bitte eine kleine Spende in Betracht.;汉化修改：;Build by: {0} 的本地化字符串。
        /// </summary>
        public static string Options_Page14_About {
            get {
                return ResourceManager.GetString("Options_Page14_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QTTabBar Einstellungen;Alle Einstellungen auf dieser Seite auf ihre Standardwerte zurücksetzen?;Alle Einstellungen auf ihre Standardwerte zurücksetzen?  Dies wirkt sich nicht auf Gruppen, Anwendungen oder Plugins aus.;Bestätigung 的本地化字符串。
        /// </summary>
        public static string OptionsDialog {
            get {
                return ResourceManager.GetString("OptionsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/indiff/qttabbar/blob/master/QTTabBar/Resources/wechat_pay.jpg 的本地化字符串。
        /// </summary>
        public static string PayPalURL {
            get {
                return ResourceManager.GetString("PayPalURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zurück;Vorwärts;Zurück zum Anfang;Vorwärts zum Ende;Nächste Registerkarte auswählen;Vorherige Registerkarte auswählen;Erste Registerkarte auswählen;Letzte Registerkarte auswählen;Zur zuletzt aktivierten Registerkarte wechseln;Neue Registerkarte öffnen;Neues Fenster öffnen;Registerkarten aus anderen Fenstern zusammenführen;Aktuelle Registerkarte schließen;Alle außer der aktuellen schließen;Links schließen;Rechts schließen;Fenster schließen;Schließen rückgängig machen;Aktuelle Registerkarte klonen;Aktuellen O [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ShortcutKeys_ActionNames {
            get {
                return ResourceManager.GetString("ShortcutKeys_ActionNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QTTabBar;{0} (Plugin) 的本地化字符串。
        /// </summary>
        public static string ShortcutKeys_Groups {
            get {
                return ResourceManager.GetString("ShortcutKeys_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/indiff/qttabbar 的本地化字符串。
        /// </summary>
        public static string SiteURL {
            get {
                return ResourceManager.GetString("SiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Schließen;Rechts schließen;Links schließen;Alles außer diesem schließen;Zu Gruppe hinzufügen;Neue Gruppe erstellen;Sperren;Dies klonen;Neues Fenster;Pfad kopieren;Eigenschaften;Tab-Historie;Gruppen;Geschlossen rückgängig machen;Zuletzt aktiviert;Kürzlich geöffnete Dateien;Ordner durchsuchen;Alles außer dem aktuellen schließen;Fenster schließen;Optionen;Entsperren;Zum Anwendungsmenü hinzufügen : ;Einträge;Abbrechen;Entwicklungszweig;Diesen Eintrag aus dem Menü entfernen;O&amp;pen, der den Ordner enthält;Tab-Labe [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TabBar_Menu {
            get {
                return ResourceManager.GetString("TabBar_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QTTabBar konnte nicht geöffnet werden
        ///
        /// &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        public static string TabBar_Message {
            get {
                return ResourceManager.GetString("TabBar_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Neue Gruppe erstellen;Gruppenname:;Alle Registerkarten hinzufügen 的本地化字符串。
        /// </summary>
        public static string TabBar_NewGroup {
            get {
                return ResourceManager.GetString("TabBar_NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fenster;Registerkarten;Tweaks;Tooltips;Allgemein;Aussehen;Maus;Tasten;Gruppen;Anwendungen;Tastenleiste;Plugins;Sprache;Über 的本地化字符串。
        /// </summary>
        public static string TabBar_Option_Genre {
            get {
                return ResourceManager.GetString("TabBar_Option_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Taskleiste;Desktop;Elemente sperren;Titelhintergrund zeichnen;Menü mit einem Klick;Tastenkombinationen für Anwendungen aktivieren 的本地化字符串。
        /// </summary>
        public static string TaskBar_Menu {
            get {
                return ResourceManager.GetString("TaskBar_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gruppen;Geschlossen rückgängig machen;Anwendungen;Zuletzt geöffnete Dateien 的本地化字符串。
        /// </summary>
        public static string TaskBar_Titles {
            get {
                return ResourceManager.GetString("TaskBar_Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 Fenster;{0} Fenster 的本地化字符串。
        /// </summary>
        public static string TrayIcon {
            get {
                return ResourceManager.GetString("TrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eine neue Version von QTTabBar wurde veröffentlicht:;Drücken Sie OK, um zur Website zu gelangen.;Ihre Version von QTTabBar ist auf dem neuesten Stand.;Neue Entwicklungsversion gefunden:;Versionsdatei nicht gefunden (404).;Unbekannter Netzwerkfehler.;Server nicht gefunden.;Server hat falsche Zeichenfolgen zurückgegeben. 的本地化字符串。
        /// </summary>
        public static string UpdateCheck {
            get {
                return ResourceManager.GetString("UpdateCheck", resourceCulture);
            }
        }
    }
}
