//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9164
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   强类型资源类，用于查找本地化字符串等。
/// </summary>
// 此类是由 StronglyTypedResourceBuilder
// 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
// 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
// (以 /str 作为命令选项)，或重新生成 VS 项目。
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources_String_tr_TR {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources_String_tr_TR() {
    }
    
    /// <summary>
    ///   返回此类使用的缓存 ResourceManager 实例。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources_String_tr_TR", typeof(Resources_String_tr_TR).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   为使用此强类型资源类的所有资源查找
    ///   重写当前线程的 CurrentUICulture 属性。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   查找类似 HarkTu 的本地化字符串。
    /// </summary>
    internal static string Author {
        get {
            return ResourceManager.GetString("Author", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Ayıraç;Önceki;Sonraki;Gruplar;Son kapatılan;Uygulamalar;Yeni Pencere;Bunu klonla;Kilitle;Kopyalama Aracı;En üstteki;Kapat;Diğerlerini kapat;Pencereyi kapat;Soldakileri kapat;Sağdakileri kapat;Bir seviye yukarı;Tekrar yükle;Ara;Opaklık;Arama kutusu;Seçenekler 的本地化字符串。
    /// </summary>
    internal static string ButtonBar_BtnName {
        get {
            return ResourceManager.GetString("ButtonBar_BtnName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Yol;İsim;Geçerli klasör yolu;Geçerli klasör adı;MD5;Öğeler;Tüm açık sekmelerin yolları 的本地化字符串。
    /// </summary>
    internal static string ButtonBar_Misc {
        get {
            return ResourceManager.GetString("ButtonBar_Misc", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Turkiye 的本地化字符串。
    /// </summary>
    internal static string Country {
        get {
            return ResourceManager.GetString("Country", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 08/15/2022 的本地化字符串。
    /// </summary>
    internal static string DateModified {
        get {
            return ResourceManager.GetString("DateModified", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Liste;Detaylar;Döşemeler;Varsayılan 的本地化字符串。
    /// </summary>
    internal static string Desktop {
        get {
            return ResourceManager.GetString("Desktop", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Tamam;İptal;&amp;Uygula;&amp;Varsayılan;&amp;Sayfayı Sıfırla;&amp;Hepsini Sıfırla;Sıfırla;Ekle;Ekle...;Sil;Seçenekler;Etkinleştir;Etkisizleştir;Geri al;Yükle...;Kaydet... 的本地化字符串。
    /// </summary>
    internal static string DialogButtons {
        get {
            return ResourceManager.GetString("DialogButtons", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Kopyala:;Taşı:;Kısayol oluştur: 的本地化字符串。
    /// </summary>
    internal static string DragDropToolTip {
        get {
            return ResourceManager.GetString("DragDropToolTip", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 İşlem başarısız.
    ///Dosya veya bağlantının geçerli olduğuna emin olun:
    ///
    ///{0};Hata - QTTabBar;Uyarı:  QTTabBar otomatik olarak etkinleştirilemedi. Manuel olarak etkinleştirmek için Alt tuşuna basıp bırakın, ardından Görünüm/Araç barları menüsünden QTTabBar&apos;ı seçin.;Etkinleştirilemiyor;Hata;QTTabBar hook kitaplığı yüklenemiyor.;QTTabBar hook kitaplığı başlatılamıyor.;Bazı özellikler çalışmayabilir. Bu sorunu çözmek için uygulamayı yeniden yüklemeniz gerekebilir.;Masaüstü bağlanamadı. Lütfen QT Tab Desktop arac [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string ErrorDialogs {
        get {
            return ResourceManager.GetString("ErrorDialogs", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Görüntü dosyaları;Dil dosyaları;Eklenti dosyaları 的本地化字符串。
    /// </summary>
    internal static string FileFilters {
        get {
            return ResourceManager.GetString("FileFilters", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Yol;Hash;Kapat;Temizle;Yenile;Her zaman üstte;Sonucu göster;Kapatıldığında temizle;Tam yol;(Hesaplanıyor...) 的本地化字符串。
    /// </summary>
    internal static string FileHashComputer {
        get {
            return ResourceManager.GetString("FileHashComputer", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Turkish 的本地化字符串。
    /// </summary>
    internal static string Language {
        get {
            return ResourceManager.GetString("Language", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Hepsi;Sol;Üst;Sağ;Alt 的本地化字符串。
    /// </summary>
    internal static string MarginDropDown {
        get {
            return ResourceManager.GetString("MarginDropDown", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Masaüstü arama;Görüntü dosyası geçersiz.
    ///
    ///Lütfen 432 x 40 px resim dosyası seçin.;Arama sonuçları;kısayol;Dosya seç;Klasör seç;Deneysel;dummy 的本地化字符串。
    /// </summary>
    internal static string Misc_Strings {
        get {
            return ResourceManager.GetString("Misc_Strings", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Windows Gezgini&apos;nin davranışını değiştirin.;Tek Pencere modu;Yeni pencereleri yeni sekme olarak yakala;Yeni pencereleri yakalama;Yeni pencereler ve sekmeler için varsayılan konum;Oturum kaydediliyor;Her seferinde yeni bir oturum başlat;Önceki oturumdaki tüm sekmeleri geri yükle;Önceki oturumdan yalnızca kilitli sekmeleri geri yükle;Kapat düğmesine basıldığında;Pencereyi kapat;Geçerli sekmeyi kapat;Kilidi açık tüm sekmeleri kapat;Tıklandığında pencereyi Görev Tepsisine gönder.;Kapat;Küçült 的本地化字符串。
    /// </summary>
    internal static string Options_Page01_Window {
        get {
            return ResourceManager.GetString("Options_Page01_Window", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Sekme seçeneklerini değiştir.;Yeni sekme aç:;Geçerli sekme kapatıldığında, şuna geç:;Derhal yeni sekmelere geç;Mevcut sekmeleri yeniden kullan;Belirsiz sekmeleri yeniden adlandır;Fare bir sekmenin üzerine sürüklendiğinde,;Geçiş yap;Alt Klasör İpucu menüsünü göster;Sekme simgeleri;Sekmelerde klasör simgelerini göster;Simge tıklandığında Alt Klasör İpucu menüsünü göster;Simgede sürücü harfini göster;Kapat düğmesi;Sekmelerde kapat düğmesini göster;Yalnızca &apos;Alt&apos; tuşu basılıyken;Yalnızca fareyle üzerine gelindi [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page02_Tabs {
        get {
            return ResourceManager.GetString("Options_Page02_Tabs", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Liste Görünümü ince ayarlarını etkinleştirir veya devre dışı bırak.;Liste Görünümü ile kullanılabilen ince ayarlar;Tüm görünüm modlarında sütun başlıklarını görüntüle (Windows Vista/7);Kitaplık klasörleri için standart dosya sistemi görünümünü kullan (Windows 7);Dosyaları yeniden adlandırırken dosya uzantısının seçimini kaldır (Windows XP);Yeniden adlandırırken F2 ile seçimi değiştir;Ok tuşlarıyla seçimi taşırken kaydır;Backspace bir seviye yukarı çıkar (Windows Vista/7);Shift tuşunu basılı tutarken fare te [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page03_Tweaks {
        get {
            return ResourceManager.GetString("Options_Page03_Tweaks", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Alt Klasör ve Önizleme araç ipuçlarının davranışını değiştirin.;Alt Klasör İpuçları;Alt Klasör İpuçlarını Etkinleştir;Sadece Shift tuşu aşağıdayken;Dosyaları göster;Menü öğeleri üzerinde fareyle gezinirken önizleme araç ipuçlarını göster;Önizleme ipuçları;Önizleme araç ipuçlarını etkinleştir;Sadece Shift tuşu aşağıdayken;Resimlerin altındaki dosya bilgilerini göster;Maksimum Genişlik x Yükseklik:;Yazı tipi:;Metin dosya türleri;Görüntü ve Video dosya türleri 的本地化字符串。
    /// </summary>
    internal static string Options_Page04_Tooltips {
        get {
            return ResourceManager.GetString("Options_Page04_Tooltips", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 QTTabBar genel davranış seçenekleri;Görev barı entegrasyonu;Görev barında sekme önizlemelerini göster;Tarih;Kapatılan sekmelerin geçmişini tut;Şimdi Temizle;Açılan dosyaların geçmişini tut;Ağ;Ağ Zaman Aşımı (Sistem varsayılanı için 0 girin):;Güncellemeleri periyodik olarak kontrol edin;Şimdi kontrol et;Dışa Aktar;Dışa Aktarma Ayarları...;Dosya geçmişi temizlensin mi?;Sekme geçmişi temizlensin mi?;Ses;Sesi etkinleştir;Günlüğü etkinleştir 的本地化字符串。
    /// </summary>
    internal static string Options_Page05_General {
        get {
            return ResourceManager.GetString("Options_Page05_General", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Sekmelerin veya sekme barının görünümünü değiştirin.;Sekme resmi;Özel sekme resmini kullan:;Boyutlandırma kenar boşlukları:;Örtüşme alanı:;İçerik kenar boşlukları:;Saydam alanları test edin;Sekme boyutu;Yükseklik:;Minimum Genişlik:;Maksimum genişlik:;Boyutlandırma modu:;Esnek genişlik;Sabit boyut;Sekme metni;Metin Renkleri:;Gölge Renkleri:;Aktif Renk;Etkin Olmayan Renk;Fare Üzerindeki Renk;Metin Yazı Tipi:;Hizalama:;Sol;Merkez;Araç barı Arka Planı;Resim;Renk;Her barı ayrı ayrı görüntüleyin;Uzatma modu:;Boyu [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page06_Appearance {
        get {
            return ResourceManager.GetString("Options_Page06_Appearance", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Farklı fare eylemlerine komutlar atayın.;Bir fare bağı eklemek için, uygun hedef türünün solundaki artı simgesi üzerinde bir fare eylemi gerçekleştirin. Bir bağı kaldırmak için listeden seçin ve Sil tuşuna basın.;Diğer fare seçenekleri;Fare tekerleği, farenin altındaki pencereyi kaydırır;Hedef fare eylemi;Eylem;Herhangi bir yer;Sekme;Sekme barı Arka Planı;Klasör Bağlantısı;Dosya veya Klasör;Gezgin Arka Planı;Sol tık;Sağ tık;Orta tıklama;Çift tıklama;X1 Tıklama;X2 Tıklama;Bu fare düğmesi bu hedef için kullan [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page07_Mouse {
        get {
            return ResourceManager.GetString("Options_Page07_Mouse", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Klavye kısayollarını değiştirin.;Listeden bir eylem seçin ve ona bağlamak istediğiniz tuş hareketine basın. Bağlamayı temizlemek için Escape tuşuna basın.;Diğer klavye seçenekleri;Ctrl + Tab tuşlarına basıldığında Sekme Değiştirici penceresini göster;Eylem;Tuş vuruşu;Bu tuş zaten şuna atanmış:;Yeniden atanmalı mı?;Tuş çakışması 的本地化字符串。
    /// </summary>
    internal static string Options_Page08_Keys {
        get {
            return ResourceManager.GetString("Options_Page08_Keys", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Sekme grupları oluşturun ve yönetin.;Bir gruba Kısayol Tuşu atamak için grubu seçin ve uygun tuş hareketine basın. Bağı kaldırmak için Escape tuşuna basın.;Yeni Grup Oluştur;Dosya;Başlangıç;Kısayol tuşu;Yeni Grup;&quot;{0}&quot; grubunu aç 的本地化字符串。
    /// </summary>
    internal static string Options_Page09_Groups {
        get {
            return ResourceManager.GetString("Options_Page09_Groups", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Sık kullanılan dosyalara veya uygulamalara kısayollar oluşturun.;Bir uygulamaya Kısayol Tuşu atamak için onu seçin ve uygun tuş hareketine basın. Bağı kaldırmak için Escape tuşuna basın.;Yeni klasör Oluştur;Yol:;Argümanlar:;Çalışma dizini:;Uygulama;Kısayol tuşu;Aşağıdaki anahtar sözcükler, çalışma zamanında çift tırnaklı yol dizeleriyle değiştirilir.;Seçilen dosyalar.;Seçilen klasörler.;Seçilen dosyalar ve klasörler.;Geçerli klasör.;Seçim yoksa geçerli klasör, aksi takdirde seçilen klasör.;Yeni dosya;Bu kla [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page10_Apps {
        get {
            return ResourceManager.GetString("Options_Page10_Apps", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Düğmeler barını özelleştirin.;Düğmeler;Düğmeler barı Seçenekleri;Büyük ikonlar;Düğmelerde etiketleri göster;Açılır düğme menülerinin sırasını kilitle;Arama kutusunun boyutunu kilitle;Özel Düğme Resimleri 的本地化字符串。
    /// </summary>
    internal static string Options_Page11_ButtonBar {
        get {
            return ResourceManager.GetString("Options_Page11_ButtonBar", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Üçüncü taraf eklentileri yönetin.;Eklenti Yükle;(Devre dışı);{0} tarafından;{0} kaldırıldı.;Bu eklenti, Tamam veya Uygula&apos;ya bastığınızda yüklenecektir.;Bu eklenti, Tamam veya Uygula&apos;ya bastığınızda etkinleştirilecektir.;Tamam veya Uygula&apos;ya bastığınızda bu eklenti devre dışı bırakılacaktır.;Bu eklentinin kaldırılması aşağıdaki eklentilerin de kaldırılmasına neden olacaktır:;Devam? 的本地化字符串。
    /// </summary>
    internal static string Options_Page12_Plugins {
        get {
            return ResourceManager.GetString("Options_Page12_Plugins", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Dili değiştir.;Ana dil;Seçili dili kullan:;Dil dosyasını kullan:;Ek dil dosyaları;Dil Dosyası Düzenleyicisi;Dil Düzenleyicisini Göster...;Orijinal;Çevrildi;Tüm girişler orijinal değerlerine sıfırlansın mı?;Dosya kaydedilirken hata oluştu.;简体中文;English;Deutsch;Português;Français 的本地化字符串。
    /// </summary>
    internal static string Options_Page13_Language {
        get {
            return ResourceManager.GetString("Options_Page13_Language", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 İlgili personel ve sürüm bilgilerini görüntüleyin.;Kaynak kodu {0};Ana geliştiriciler:;Diğer geliştiriciler:;Simge ve Grafik Tasarım:;QTTabBar&apos;ı faydalı bulursanız, lütfen küçük bir bağış yapmayı düşünün.;Basitleştirilmiş Çince:;Derleme: {0} 的本地化字符串。
    /// </summary>
    internal static string Options_Page14_About {
        get {
            return ResourceManager.GetString("Options_Page14_About", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 QTTabBar Seçenekleri;Bu sayfadaki tüm seçenekler varsayılan değerlerine sıfırlansın mı?;Tüm seçenekler varsayılan değerlerine sıfırlansın mı? Bu, Grupları, Uygulamaları veya Eklentileri etkilemeyecektir.;Onayla 的本地化字符串。
    /// </summary>
    internal static string OptionsDialog {
        get {
            return ResourceManager.GetString("OptionsDialog", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 https://github.com/indiff/qttabbar/blob/master/QTTabBar/Resources/wechat_pay.jpg 的本地化字符串。
    /// </summary>
    internal static string PayPalURL {
        get {
            return ResourceManager.GetString("PayPalURL", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Geri dön ( Alt + Left );ileri git ( Alt + Right );Başa dön;Sona git;Sonraki sekmeyi seç;Önceki sekmeyi seç;İlk sekmeyi seç;Son sekmeyi seç;En son etkinleştirilen sekmeye geç;Yeni sekme aç;Yeni pencere aç;Diğer pencerelerden sekmeleri birleştir;Geçerli sekmeyi kapat;Geçerli hariç hepsini kapat;Soldakileri kapat;Sağdakileri kapat;Pencereyi kapat;Kapatmayı geri al;Geçerli sekmeyi klonla;Geçerli klasörü yeni pencerede aç;Geçerliyi kilitle / kilidini aç;Tümünü kilitle / kilidini aç;Klasöre göz at;Yeni Grup Oluşt [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string ShortcutKeys_ActionNames {
        get {
            return ResourceManager.GetString("ShortcutKeys_ActionNames", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 QTTabBar;{0} (Plugin) 的本地化字符串。
    /// </summary>
    internal static string ShortcutKeys_Groups {
        get {
            return ResourceManager.GetString("ShortcutKeys_Groups", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 https://github.com/indiff/qttabbar 的本地化字符串。
    /// </summary>
    internal static string SiteURL {
        get {
            return ResourceManager.GetString("SiteURL", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Kapat;Sağdakileri kapat;Soldakileri kapat;Bu hariç hepsini kapat;Gruba ekle;Yeni Grup Oluştur;Kilitle;Bunu klonla;Yeni Pencere;Yolu kopyala;Özellikler;Sekme geçmişi;Gruplar;Kapatmayı geri al;Son kullanılan;Son açılan dosyalar;Klasöre göz at;Geçerli hariç hepsini kapat;Pencereyi kapat;Ayarlar;Kilidini aç;(&amp;A) uygulama menüsüne ekle;Öğeler;İptal;Dallar;Bu öğeyi menüden kaldır;(&amp;P) klasörünü aç;Sekme etiketi;Sekme sıralaması;İsim;Yol;Kullanım;Araç barlarını Kilitle;Diğer pencerelerin sekmelerini birleştir;Ters [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string TabBar_Menu {
        get {
            return ResourceManager.GetString("TabBar_Menu", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 QTTabBar açamıyor
    ///
    /// &quot;{0}&quot;. 的本地化字符串。
    /// </summary>
    internal static string TabBar_Message {
        get {
            return ResourceManager.GetString("TabBar_Message", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Yeni Grup Oluştur;Grup ismi:;Tüm sekmeleri ekle 的本地化字符串。
    /// </summary>
    internal static string TabBar_NewGroup {
        get {
            return ResourceManager.GetString("TabBar_NewGroup", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Pencere;Sekmeler;İnce ayarlar;İpuçları;Genel;Görünüş;Fare;Kısayollar;Gruplar;Uygulamalar;Düğmeler Barı;Eklentiler;Dil;Hakkında 的本地化字符串。
    /// </summary>
    internal static string TabBar_Option_Genre {
        get {
            return ResourceManager.GetString("TabBar_Option_Genre", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Görev barı (&amp;T);Masaüstü (&amp;D);Öğeleri kilitle (&amp;L);Başlık arka planını çiz (&amp;B);Menüyü göster (&amp;O);Uygulama kısayolları (&amp;A) 的本地化字符串。
    /// </summary>
    internal static string TaskBar_Menu {
        get {
            return ResourceManager.GetString("TaskBar_Menu", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Gruplar;Kapatmayı geri al;Uygulamalar;Son açılan dosyalar 的本地化字符串。
    /// </summary>
    internal static string TaskBar_Titles {
        get {
            return ResourceManager.GetString("TaskBar_Titles", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 1 pencere;{0} pencere 的本地化字符串。
    /// </summary>
    internal static string TrayIcon {
        get {
            return ResourceManager.GetString("TrayIcon", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 QTTabBar&apos;ın yeni bir sürümü yayınlandı:;Web sitesine gitmek için Tamam&apos;a basın.;QTTabBar sürümünüz güncel.;Yeni geliştirme sürümü bulundu:;Sürüm dosyası bulunamadı (404).;Bilinmeyen ağ hatası.;Sunucu bulunamadı.;Sunucu yanlış dizeler döndürdü. 的本地化字符串。
    /// </summary>
    internal static string UpdateCheck {
        get {
            return ResourceManager.GetString("UpdateCheck", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 DevBuild: 2022/8/15 19:01:42 (2.0.50727.9164) 的本地化字符串。
    /// </summary>
    internal static string Version_QTTabBar {
        get {
            return ResourceManager.GetString("Version_QTTabBar", resourceCulture);
        }
    }
}
