//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9164
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   强类型资源类，用于查找本地化字符串等。
/// </summary>
// 此类是由 StronglyTypedResourceBuilder
// 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
// 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
// (以 /str 作为命令选项)，或重新生成 VS 项目。
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources_String_ru_RU {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources_String_ru_RU() {
    }
    
    /// <summary>
    ///   返回此类使用的缓存 ResourceManager 实例。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources_String_ru_RU", typeof(Resources_String_ru_RU).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   为使用此强类型资源类的所有资源查找
    ///   重写当前线程的 CurrentUICulture 属性。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   查找类似 AHOHNMYC 的本地化字符串。
    /// </summary>
    internal static string Author {
        get {
            return ResourceManager.GetString("Author", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Разделитель;Назад;Вперед;Группы;Последние закрытые;Приложения;Новое окно;Дублировать;Заблокировать;Копировать;Поверх всех;Закрыть;Закрыть все, кроме текущей;Закрыть окно;Закрыть все слева;Закрыть все справа;На уровень выше;Обновить;Поиск;Прозрачность;Панель поиска;Настройки 的本地化字符串。
    /// </summary>
    internal static string ButtonBar_BtnName {
        get {
            return ResourceManager.GetString("ButtonBar_BtnName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Путь;Имя;Путь текущей папки;Имя текущей папки;MD5; элементов;Пути всех открытых вкладок 的本地化字符串。
    /// </summary>
    internal static string ButtonBar_Misc {
        get {
            return ResourceManager.GetString("ButtonBar_Misc", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 RU 的本地化字符串。
    /// </summary>
    internal static string Country {
        get {
            return ResourceManager.GetString("Country", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 10/20/2022 的本地化字符串。
    /// </summary>
    internal static string DateModified {
        get {
            return ResourceManager.GetString("DateModified", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Список;Подробности;Значки;По умолчанию 的本地化字符串。
    /// </summary>
    internal static string Desktop {
        get {
            return ResourceManager.GetString("Desktop", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 ОК;Отмена;&amp;Применить;&amp;По умолчанию;Сбросить &amp;страницу;&amp;Сбросить все;Сброс;Добавить;Добавить...;Удалить;Настройки;Включить;Выключить;Отменить;Загрузить...;Сохранить... 的本地化字符串。
    /// </summary>
    internal static string DialogButtons {
        get {
            return ResourceManager.GetString("DialogButtons", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Копировать в:;Переместить в:;Сделать ярлык в: 的本地化字符串。
    /// </summary>
    internal static string DragDropToolTip {
        get {
            return ResourceManager.GetString("DragDropToolTip", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Действие не выполнено.
    ///Пожалуйста, проверьте, что файл или объект, на который указывает ярлык, существует:
    ///
    ///{0};Ошибка - QTTabBar;Внимание:  Не удалось автоматически включить QTTabBar. Чтобы включить его вручную, нажмите и отпустите Alt, а затем отметьте QTTabBar в меню Вид-Панели.;Не удалось включить;Ошибка;Не удалось загрузить библиотеку захвата QTTabBar.;Не удалось инициализировать библиотеку захвата QTTabBar.;Некоторые возможности могут быть недоступны. Чтобы это починить, возможно, потребуется переу [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string ErrorDialogs {
        get {
            return ResourceManager.GetString("ErrorDialogs", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Файлы изображений;Файлы локализаций;Файлы дополнений 的本地化字符串。
    /// </summary>
    internal static string FileFilters {
        get {
            return ResourceManager.GetString("FileFilters", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Путь;Хэш;Закрыть;Очистить;Обновить;Всегда сверху;Показать результат;Очищать при закрытии;Полный путь;(Вычисляется...) 的本地化字符串。
    /// </summary>
    internal static string FileHashComputer {
        get {
            return ResourceManager.GetString("FileHashComputer", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 中文简体 的本地化字符串。
    /// </summary>
    internal static string Language {
        get {
            return ResourceManager.GetString("Language", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Все;Слева;Сверху;Справа;Снизу 的本地化字符串。
    /// </summary>
    internal static string MarginDropDown {
        get {
            return ResourceManager.GetString("MarginDropDown", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Desktop Search;Изображение не подходит.
    ///
    ///Пожалуйста, выберите изображение размером 432x40 пикселей.;Результаты поиска в;ярлык;Выберите файл;Выберите папку;Экспериментально;заглушка 的本地化字符串。
    /// </summary>
    internal static string Misc_Strings {
        get {
            return ResourceManager.GetString("Misc_Strings", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Поведение Проводника;Режим одного окна;Захватывать новые окна Проводника во вкладки;Не захватывать новые окна;Место по умолчанию для новых окон и вкладок;Сохранение сессии;Не сохранять сессию;Восстанавливать все вкладки;Восстанавливать только закрепленные вкладки;Действие при закрытии окна;Закрыть окно;Закрыть текущую вкладку;Закрыть незакрепленные вкладки;Прятать окно в системный лоток при;Закрытии;Сворачивании;Сделать кнопку + синей 的本地化字符串。
    /// </summary>
    internal static string Options_Page01_Window {
        get {
            return ResourceManager.GetString("Options_Page01_Window", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Настройки вкладок;Открыть новую вкладку:;При закрытии вкладки переключиться на:;Переключаться на новые вкладки;Использовать существующие вкладки;Переименовать неоднозначные вкладки;При drag&apos;n&apos;drop на вкладку;переключиться на неё;показать меню с подпапками;Иконки вкладок;Показывать иконки папок на вкладках;Показывать меню с подпапками при нажатии на иконку;Показывать букву диска на вкладке;Кнопка закрытия;Показывать кнопку закрытия;Только с зажатым Alt;Только при наведении мыши;Панель вкладок;Показывать кноп [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page02_Tabs {
        get {
            return ResourceManager.GetString("Options_Page02_Tabs", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Тонкие настройки списка в Проводнике;Настройки для всех версий Проводника;Показывать столбцы во всех режимах отображения (Windows Vista/7);Использовать стандартное отображание для папок Библиотеки (Windows 7);Не выделять расширение файла при переименовании (Windows XP);Не переключать выделение при нажатии F2 при переименовании;Wrap around when moving the selection with the arrow keys;Переходить на уровень вверх по нажатию Backspace (Windows Vista/7);Горизонтальная прокрутка списка колесиком мышки с зажатым  [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page03_Tweaks {
        get {
            return ResourceManager.GetString("Options_Page03_Tweaks", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Поведение подсказок подкаталогов и предпросмотра;Подсказки подкаталогов;Включить подсказки подкаталогов;Только с зажатым Shift;Показывать файлы;Показывать подсказки предпросмотра при наведении курсора мыши;Подсказки предпросмотра;Включить подсказки предпросмотра;Только с зажатым Shift;Показывать информацию о файле под изображением;Максимальная Ширина x Высота:;Шрифт:;Текстовые типы файлов;Изображения и видео 的本地化字符串。
    /// </summary>
    internal static string Options_Page04_Tooltips {
        get {
            return ResourceManager.GetString("Options_Page04_Tooltips", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Поведение QTTabBar;Интеграция с Панелью задач;Показать предпросмотр вкладок на Панели задач;История;Хранить историю закрытых вкладок;Очистить;Хранить историю открытия файлов;Сеть;Таймаут подключения (0 - определяется системой):;Периодически проверять обновления;Проверить сейчас;Резервные копии;Сохранить настройки...;Очистить историю файлов?;Очистить историю вкладок?;Звуки;Включить звуки;Включить журнал 的本地化字符串。
    /// </summary>
    internal static string Options_Page05_General {
        get {
            return ResourceManager.GetString("Options_Page05_General", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Внешний вид вкладок и панели вкладок;Изображение вкладки;Использовать своё изображение:;Поля изображения:;Область перекрытия:;Отступ содержимого:;Проверять зоны прозрачности;Размер вкладки;Высота:;Ширина от:;Ширина до:;Ширина:;по содержимому;одинаковая;Текст вкладки;Цвета текста:;Цвета теней:;Активная вкладка;Неактивная вкладка;Под курсором;Шрифт:;Положение:;Слева;По центру;Фон панели инструментов;Изображение;Заливка цветом;Отдельное изображение для каждой панели;Режим растягивания:;Поля изображения:;Файл ш [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page06_Appearance {
        get {
            return ResourceManager.GetString("Options_Page06_Appearance", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Управление Проводником мышкой;Чтобы добавить привязку, кликните по кнопке + желаемой кнопкой мыши, зажав желаемые клавиши-модификаторы (Ctrl, Shift).  Для удаления привязки, выберите её и нажмите клавишу Delete.;Настройки поведения мыши;Прокручивать колесиком мыши содержимое окна под курсором;Аккорд;Действие;Везде;Вкладка;Панель вкладок;Ссылка на каталог;Файл или Папка;Фон Проводника;Левая кнопка;Правая кнопка;Средняя кнопка;Двойной клик;X1 Клик;X2 Клик;Нажатая кнопка мыши не может быть использована в этом  [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page07_Mouse {
        get {
            return ResourceManager.GetString("Options_Page07_Mouse", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Горячие клавиши;Выберите действие из списка и нажмите сочетание клавиш, которое вы хотите ему назначить.  Нажмите Escape, чтобы очистить привязку.;Другие настройки клавиатуры;Показывать окно переключения по вкладкам по Ctrl+Tab ;Действие;Сочетание клавиш;Это сочетание уже назначено на:;Вы хотите его переназначить?;Сочетание уже используется 的本地化字符串。
    /// </summary>
    internal static string Options_Page08_Keys {
        get {
            return ResourceManager.GetString("Options_Page08_Keys", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Управление группами вкладок;Для того, чтобы назначить группе сочетание клавиш, выберите группу и нажмите желаемое сочетание клавиш.  Для сброса сочетания клавиш нажмите Escape.;Создать группу;Папка;Автозапуск;Сочетание клавиш;Новая группа;Открыть группу &quot;{0}&quot; 的本地化字符串。
    /// </summary>
    internal static string Options_Page09_Groups {
        get {
            return ResourceManager.GetString("Options_Page09_Groups", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Ярлыки для часто используемых файлов и приложений;Для того, чтобы назначить приложению сочетание клавиш, выберите его и нажмите желаемое сочетание клавиш.  Для сброса сочетания клавиш нажмите Escape.;Новая папка;Путь:;Аргументы:;Рабочая папка:;Программа;Сочетание клавиш;Символы подстановки, при запуске будут заменены на соответствующие пути в двойных кавычках;выбранные файлы;выбранные папки;выбранные файлы и папки;текущая папка;выбранная папка, если ничего не выбрано - текущая папка;Новая папка;Удалить папк [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page10_Apps {
        get {
            return ResourceManager.GetString("Options_Page10_Apps", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Панель кнопок;Кнопки;Настройки Панели кнопок;Большие иконки;Показывать названия кнопок;Зафиксировать порядок меню в выпадающих кнопках;Зафиксировать размер панели поиска;Свой файл с иконками 的本地化字符串。
    /// </summary>
    internal static string Options_Page11_ButtonBar {
        get {
            return ResourceManager.GetString("Options_Page11_ButtonBar", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Управление сторонними плагинами;Установить;(Отключен);автор: {0};{0} был удален.;Плагин будет установлен после нажатия ОК или Применить.;Плагин будет включен после нажатия ОК или Применить.;Плагин будет отключен после нажатия ОК или Применить.;При удалении этого плагина также будут удалены плагины:;Продолжить?;Включить;Отключить 的本地化字符串。
    /// </summary>
    internal static string Options_Page12_Plugins {
        get {
            return ResourceManager.GetString("Options_Page12_Plugins", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Изменить язык;Язык;Встроенный:;Из файла:;Локализации плагинов;Редактор локализации;Показать редактор локализации...;Исходная;Переведенная;Сбросить все строки к исходным значениям?;Ошибка при сохранении файла.;Упрощенный китайский;Английский;Немецкий 的本地化字符串。
    /// </summary>
    internal static string Options_Page13_Language {
        get {
            return ResourceManager.GetString("Options_Page13_Language", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Информация о версии и разработчиках;Автор исходного проекта {0};Ведущие разработчики:;Разработчики:;Иконки и графика:;Если вы сочли QTTabBar полезным, пожалуйста, пожертвуйте на продолжение разработки.;Китайская версия:;Собрал программу: {0} 的本地化字符串。
    /// </summary>
    internal static string Options_Page14_About {
        get {
            return ResourceManager.GetString("Options_Page14_About", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Настройки QTTabBar;Сбросить все настройки на этой странице на значение по умолчанию?;Сбросить все настройки на значения по умолчанию?   Настройки Групп, Приложений, и Плагинов не будут затронуты;Подтверждение 的本地化字符串。
    /// </summary>
    internal static string OptionsDialog {
        get {
            return ResourceManager.GetString("OptionsDialog", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 https://github.com/indiff/qttabbar/blob/master/QTTabBar/Resources/wechat_pay.jpg 的本地化字符串。
    /// </summary>
    internal static string PayPalURL {
        get {
            return ResourceManager.GetString("PayPalURL", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Назад;Вперед;Назад в начало истории;Вперед в конец истории;Выбрать следующую вкладку;Выбрать предыдущую вкладку;Выбрать первую вкладку;Выбрать последнюю вкладку;Переключиться на последнюю активную вкладку;Открыть новую вкладку;Открыть новое окно;Перенести вкладки из других окон;Закрыть текущую вкладку;Закрыть все, кроме текущей;Закрыть вкладки слева;Закрыть вкладки справа;Закрыть окно;Восстановить закрытые вкладки;Дублировать текущую вкладку;Открыть текущую папку в новом окне;Заблокировать / разблокировать  [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string ShortcutKeys_ActionNames {
        get {
            return ResourceManager.GetString("ShortcutKeys_ActionNames", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 QTTabBar;{0} (Плагин);用户指令 的本地化字符串。
    /// </summary>
    internal static string ShortcutKeys_Groups {
        get {
            return ResourceManager.GetString("ShortcutKeys_Groups", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 https://github.com/indiff/qttabbar 的本地化字符串。
    /// </summary>
    internal static string SiteURL {
        get {
            return ResourceManager.GetString("SiteURL", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Закрыть;Закрыть все справа;Закрыть все слева;Закрыть все, кроме этой;Добавить в группу;Создать группу;Заблокировать;Дублировать;Новое окно;Копировать путь;Свойства;История вкладки;Группы;Недавно закрытые;Последняя активная;Последние открытые файлы;Обзор папок;Закрыть все, кроме текущей;Закрыть окно;Настройки;Разблокировать;Добавить в меню приложений: ; объектов;Отмена;Ветки;Удалить этот пункт из меню;О&amp;ткрыть содержащую объект папку;Название вкладки;Упорядочить вкладки;Имя;Путь;Активность;Заблокировать пане [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string TabBar_Menu {
        get {
            return ResourceManager.GetString("TabBar_Menu", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Не удалось открыть QTTabBar
    ///
    /// &quot;{0}&quot;. 的本地化字符串。
    /// </summary>
    internal static string TabBar_Message {
        get {
            return ResourceManager.GetString("TabBar_Message", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Создать группу;Название группы:;Добавить все вкладки 的本地化字符串。
    /// </summary>
    internal static string TabBar_NewGroup {
        get {
            return ResourceManager.GetString("TabBar_NewGroup", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Окна;Вкладки;Тонкие настройки;Подсказки;Общее;Внешний вид;Мышь;Клавиатура;Группы;Приложения;Панель кнопок;Плагины;Язык;О программе 的本地化字符串。
    /// </summary>
    internal static string TabBar_Option_Genre {
        get {
            return ResourceManager.GetString("TabBar_Option_Genre", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Панель задач;Рабочий стол;Заблокированные;Отрисовать фон заголовка;Меню по одному нажатию;Включить горячие клавиши длч приложений 的本地化字符串。
    /// </summary>
    internal static string TaskBar_Menu {
        get {
            return ResourceManager.GetString("TaskBar_Menu", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Группы;Недавно закрытые;Приложения;Последние открытые файлы 的本地化字符串。
    /// </summary>
    internal static string TaskBar_Titles {
        get {
            return ResourceManager.GetString("TaskBar_Titles", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 1 окно;{0} окон;恢复所有;关闭所有 的本地化字符串。
    /// </summary>
    internal static string TrayIcon {
        get {
            return ResourceManager.GetString("TrayIcon", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Вышла новая версия QTTabBar:;Нажмите ОК, чтобы перейти на сайт.;Вы пользуетесь самой свежей версией QTTabBar.;Есть новая разрабатываемая версия:;Не удалось проверить версию (ошибка 404).;Невероятные проблемы с сетью.;Сервер не найден.;Сервер вернул в ответе какую-то дичь. 的本地化字符串。
    /// </summary>
    internal static string UpdateCheck {
        get {
            return ResourceManager.GetString("UpdateCheck", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 0.0.1 的本地化字符串。
    /// </summary>
    internal static string Version_LangFile {
        get {
            return ResourceManager.GetString("Version_LangFile", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 DevBuild: 2022/10/11 下午 07:45:49 (2.0.50727.9164) 的本地化字符串。
    /// </summary>
    internal static string Version_QTTabBar {
        get {
            return ResourceManager.GetString("Version_QTTabBar", resourceCulture);
        }
    }
}
