//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9164
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   强类型资源类，用于查找本地化字符串等。
/// </summary>
// 此类是由 StronglyTypedResourceBuilder
// 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
// 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
// (以 /str 作为命令选项)，或重新生成 VS 项目。
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources_String_es_ES {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources_String_es_ES() {
    }
    
    /// <summary>
    ///   返回此类使用的缓存 ResourceManager 实例。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources_String_es_ES", typeof(Resources_String_es_ES).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   为使用此强类型资源类的所有资源查找
    ///   重写当前线程的 CurrentUICulture 属性。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   查找类似 Damián Roig 的本地化字符串。
    /// </summary>
    internal static string Author {
        get {
            return ResourceManager.GetString("Author", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Separador;Atrás;Adelante;Grupos;Cerrado recientemente;Aplicaciones;Nueva ventana;Clonar pestaña;Bloquear;Herramienta de copia;Encima de todo;Cerrar pestaña;Cerrar todas menos la actual;Cerrar la ventana;Cerrar pestañas a la izquierda;Cerrar pestañas a la derecha;Subir un nivel;Recargar;Buscar;Opacidad;Cuadro de búsqueda;Opciones 的本地化字符串。
    /// </summary>
    internal static string ButtonBar_BtnName {
        get {
            return ResourceManager.GetString("ButtonBar_BtnName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Ruta;Nombre;Ruta de la carpeta actual;Nombre de la carpeta actual;MD5; elementos;Rutas de todas las pestañas abiertas 的本地化字符串。
    /// </summary>
    internal static string ButtonBar_Misc {
        get {
            return ResourceManager.GetString("ButtonBar_Misc", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 España 的本地化字符串。
    /// </summary>
    internal static string Country {
        get {
            return ResourceManager.GetString("Country", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 08/15/2022 的本地化字符串。
    /// </summary>
    internal static string DateModified {
        get {
            return ResourceManager.GetString("DateModified", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Lista;Detalles;Mosaicos;Predeterminado 的本地化字符串。
    /// </summary>
    internal static string Desktop {
        get {
            return ResourceManager.GetString("Desktop", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Aceptar;Cancelar;&amp;Aplicar;&amp;Predeterminado;Rest. &amp;Página;&amp;Rest. Todo;Restaurar;Añadir;Añadir...;Eliminar;Opciones;Activar;Desactivar;Deshacer;Cargar...;Guardar... 的本地化字符串。
    /// </summary>
    internal static string DialogButtons {
        get {
            return ResourceManager.GetString("DialogButtons", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Copiar a:;Mover a:;Crear acceso directo en: 的本地化字符串。
    /// </summary>
    internal static string DragDropToolTip {
        get {
            return ResourceManager.GetString("DragDropToolTip", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 La operación ha fallado.
    ///Por favor, asegúrese de que el archivo o el destino del enlace existe:
    ///
    ///{0};Error - QTTabBar;Advertencia:  No se ha podido activar automáticamente QTTabBar. Para activarla manualmente, en ventana de Panel de Control, pulse y suelte la tecla Alt, y seleccione QTTabBar en el menú Ver/Barra de herramientas.;No se ha podido activar;Error;No se ha podido cargar la librería de enganche/hook de QTTabBar.;No se ha podido inicializar la biblioteca de enganche/hook de QTTabBar.;Algunas car [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string ErrorDialogs {
        get {
            return ResourceManager.GetString("ErrorDialogs", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Archivos de imagen;Archivos de idioma;Archivos de complementos 的本地化字符串。
    /// </summary>
    internal static string FileFilters {
        get {
            return ResourceManager.GetString("FileFilters", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Ruta;Hash;Cerrar;Borrar;Actualizar;Siempre arriba;Mostrar resultado;Borrar al cerrar;Ruta completa;(Calculando...) 的本地化字符串。
    /// </summary>
    internal static string FileHashComputer {
        get {
            return ResourceManager.GetString("FileHashComputer", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 español 的本地化字符串。
    /// </summary>
    internal static string Language {
        get {
            return ResourceManager.GetString("Language", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Todo;Izquierda;Arriba;Derecha;Abajo 的本地化字符串。
    /// </summary>
    internal static string MarginDropDown {
        get {
            return ResourceManager.GetString("MarginDropDown", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Búsqueda en el escritorio;El archivo de imagen no es válido
    ///
    ///Por favor, especifique un archivo de imagen de 432 x 40 px.;Resultados de la búsqueda en;acceso directo;Elija su archivo;Elija su carpeta;Experimental;dummy 的本地化字符串。
    /// </summary>
    internal static string Misc_Strings {
        get {
            return ResourceManager.GetString("Misc_Strings", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Cambia el comportamiento de las ventanas del Explorador de Windows.;Modo de ventana única;Capturar ventanas del Explorador como pestañas;No capturar ventanas del Explorador;Ubicación predeterminada de las nuevas ventanas y pestañas;Guardar la sesión;Iniciar una nueva sesión cada vez;Restablecer todas las pestañas de la sesión anterior;Restablecer solo las pestañas bloqueadas de la sesión anterior;Al hacer clic en el botón cerrar de la ventana;Cerrar la ventana;Cerrar la pestaña actual;Cerrar todas las pesta [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page01_Window {
        get {
            return ResourceManager.GetString("Options_Page01_Window", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Cambia las opciones relacionadas con las pestañas.;Abrir nuevas pestañas:;Al cerrar la pestaña actual, cambiar a la:;Cambiar a nuevas pestañas inmediatamente;Reutilizar las pestañas existentes;Renombrar pestañas ambiguas (equívocas);Al arrastrar el cursor sobre una pestaña,;Cambiar a ella;Mostrar el menú de consejos;Iconos de pestañas;Mostrar los iconos de las carpetas en las pestañas;Mostrar el menú de la carpeta al hacer clic en el icono;Mostrar la letra de la unidad en el icono;Botón cerrar;Mostrar el bo [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page02_Tabs {
        get {
            return ResourceManager.GetString("Options_Page02_Tabs", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Activa o desactiva los ajustes de la Vista de Lista del Explorador.;Ajustes que se pueden utilizar con cualquiera de las Vistas de Lista;Mostrar las cabeceras de las columnas en todos los modos de vista (Windows Vista/7);Utilizar la vista estándar del sistema de archivos para las carpetas de la Biblioteca (Windows 7);No seleccionar la extensión del archivo al cambiar nombre (Windows XP);Alternar selección entre partes del nombre del archivo con F2 al cambiar nombre ;Envolver al mover la selección con las te [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page03_Tweaks {
        get {
            return ResourceManager.GetString("Options_Page03_Tweaks", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Cambia el comportamiento de la información sobre herramientas de la subcarpeta y de la vista previa.;Consejos en la subcarpeta;Activar los consejos en la subcarpeta;Solo con la tecla Mayús presionada;Mostrar archivos;Mostrar información de la vista previa al sobreponer el cursor en los elementos del menú;Información sobre la vista previa;Activar la información sobre la vista previa;Sólo con la tecla Mayús pulsada;Mostrar la información del archivo debajo de las imágenes;Ancho x Alto máximo:;Fuente:;Tipos de [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page04_Tooltips {
        get {
            return ResourceManager.GetString("Options_Page04_Tooltips", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Opciones generales para el comportamiento de QTTabBar.;Integración en la Barra de Tareas;Mostrar vistas previas de las pestañas en la Barra de Tareas;Historial;Máximo de pestañas cerradas en historial;Borrar ahora;Máximo de archivos abiertos en el historial;Red;Tiempo de espera de red (introduzca 0 para el sistema por defecto):;Comprobar las actualizaciones periódicamente;Comprobar;Exportar;Exportar Ajustes...;¿Borrar el historial de archivos?;¿Borrar el historial de pestañas?;Sonido;Activar sonido;Activar  [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page05_General {
        get {
            return ResourceManager.GetString("Options_Page05_General", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Cambia la apariencia de las pestañas o de la Barra de Pestañas.;Imagen de la pestaña;Usar una imagen de pestaña personalizada:;Márgenes de tamaño:;Área de superposición:;Márgenes de contenido:;Prueba de impacto de áreas transparentes;Tamaño de la pestaña;Altura:;Anchura mínima:;Anchura máxima:;Modo de tamaño:;Anchura completa;Mismo tamaño;Texto de la pestaña;Colores del texto:;Colores de sombra:;Color activo;Color inactivo;Color al pasar el ratón;Fuente del texto:;Alineación:;Izquierda;Centro;Fondo de la ba [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page06_Appearance {
        get {
            return ResourceManager.GetString("Options_Page06_Appearance", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Asigna comandos a diferentes acciones del ratón.;Para añadir un vínculo al ratón, pulse sobre el gesto de la izquierda y seleccione la acción en el desplegable de la derecha. Para eliminar un vínculo, seleccione el gesto y pulse la tecla Supr.;Otras opciones del ratón;La rueda del ratón desplaza la ventana bajo el ratón;Gestos del ratón;Acción;Dondequiera;Pestaña;Fondo Barra de Pestañas;Enlaces Carpetas (Link Folder);Archivo o Carpeta;Fondo Explorador;Clic izquierdo;Clic derecho;Clic medio;Doble clic;X1 Cli [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page07_Mouse {
        get {
            return ResourceManager.GetString("Options_Page07_Mouse", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Cambia los atajos de teclado.;Seleccione una acción de la lista y pulse el atajo de teclado que le desea vincular. Pulse Esc para borrar la vinculación.;Otras opciones de teclado;Mostrar la ventana del Selector de Pestañas al pulsar Ctrl + Tab;Acción;Atajo de teclado;El atajo ya está asignado a:;¿Desea reasignarlo?;Conflicto en el atajo de teclado 的本地化字符串。
    /// </summary>
    internal static string Options_Page08_Keys {
        get {
            return ResourceManager.GetString("Options_Page08_Keys", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Crea y gestiona grupos de pestañas.;Para asignar un atajo de teclado a un grupo, selecciónelo y pulse el atajo correspondiente.  Pulse Esc para borrar la vinculación.;Crear Nuevo Grupo;Carpeta;Inicio;Atajo de teclado;Nuevo Grupo;Abrir grupo &quot;{0}&quot; 的本地化字符串。
    /// </summary>
    internal static string Options_Page09_Groups {
        get {
            return ResourceManager.GetString("Options_Page09_Groups", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Crea accesos directos a los archivos o aplicaciones más utilizados.;Para asignar un atajo de teclado a una aplicación, selecciónela y pulse el atajo correspondiente.  Pulse Esc para borrar la vinculación.;Crear Nueva Carpeta;Ruta:;Argumentos:;Directorio de trabajo:;Aplicación;Tecla de acceso directo;Las siguientes palabras clave se sustituyen por cadenas de ruta con comillas dobles en tiempo de ejecución.;Archivos seleccionados.;Carpetas seleccionadas.;Archivos y carpetas seleccionados.;Carpeta actual.;Carp [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page10_Apps {
        get {
            return ResourceManager.GetString("Options_Page10_Apps", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Personaliza la Barra de Botones.;Botones;Opciones de la Barra de Botones;Iconos grandes;Mostrar etiquetas en los botones;Bloquear el orden de los menús de los botones con desplegable;Bloquear el tamaño del cuadro de búsqueda;Imágenes de botones personalizadas 的本地化字符串。
    /// </summary>
    internal static string Options_Page11_ButtonBar {
        get {
            return ResourceManager.GetString("Options_Page11_ButtonBar", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Gestiona los complementos de terceros.;Instalar;(Desactivado);por {0};{0} ha sido eliminado.;Este complemento se instalará cuando pulse Aceptar o Aplicar.;Este complemento se activará cuando pulse Aceptar o Aplicar.;Este complemento se desactivará cuando pulse Aceptar o Aplicar.;La desinstalación de este complemento también desinstalará los siguientes:;¿Proceder?;Activar;Desactivar 的本地化字符串。
    /// </summary>
    internal static string Options_Page12_Plugins {
        get {
            return ResourceManager.GetString("Options_Page12_Plugins", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Cambia el idioma.;Idioma principal;Utilizar el idioma incorporado:;Utilizar archivo de idioma:;Archivos de idioma de los complementos;Editor de archivos de idioma;Mostrar el editor de idiomas...;Original;Traducido;¿Restaurar todas las entradas a su valor original?;Error al guardar el archivo.;Chino simplificado;Inglés;Alemán 的本地化字符串。
    /// </summary>
    internal static string Options_Page13_Language {
        get {
            return ResourceManager.GetString("Options_Page13_Language", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Muestra créditos e información de la versión.;Código original de {0};Desarrolladores principales:;Otros desarrolladores:;Iconos y gráficos:;Si encuentra útil QTTabBar, por favor considere hacer una pequeña donación.;Modificación del chino.;Realizado por: {0} 的本地化字符串。
    /// </summary>
    internal static string Options_Page14_About {
        get {
            return ResourceManager.GetString("Options_Page14_About", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Opciones de QTTabBar;¿Restaurar todas las opciones de esta página a sus valores por defecto?;¿Restaurar todas las opciones a sus valores por defecto?  Esto no afectará a los Grupos, Aplicaciones o Plugins.;Confirmación 的本地化字符串。
    /// </summary>
    internal static string OptionsDialog {
        get {
            return ResourceManager.GetString("OptionsDialog", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 https://github.com/indiff/qttabbar/blob/master/QTTabBar/Resources/wechat_pay.jpg 的本地化字符串。
    /// </summary>
    internal static string PayPalURL {
        get {
            return ResourceManager.GetString("PayPalURL", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Atrás;Adelante;Atrás al inicio;Adelante al final;Seleccionar la pestaña siguiente;Seleccionar la pestaña anterior;Seleccionar la primera pestaña;Seleccionar la última pestaña;Cambiar a la última pestaña activada;Abrir una nueva pestaña;Abrir una nueva ventana;Combinar pestañas de otras ventanas;Cerrar la pestaña actual;Cerrar todas menos la actual;Cerrar pestañas a la izquierda;Cerrar pestañas a la derecha;Cerrar ventana;Deshacer cierre;Clonar la pestaña actual;Abrir la carpeta actual en una nueva ventana;B [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string ShortcutKeys_ActionNames {
        get {
            return ResourceManager.GetString("ShortcutKeys_ActionNames", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 QTTabBar;{0} (Plugin) 的本地化字符串。
    /// </summary>
    internal static string ShortcutKeys_Groups {
        get {
            return ResourceManager.GetString("ShortcutKeys_Groups", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 https://github.com/indiff/qttabbar 的本地化字符串。
    /// </summary>
    internal static string SiteURL {
        get {
            return ResourceManager.GetString("SiteURL", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Cerrar pestaña;Cerrar pestañas a la derecha;Cerrar pestañas a la izquierda;Cerrar todas menos esta;Añadir al grupo;Crear un nuevo grupo;Bloquear;Clonar pestaña;Nueva ventana;Copiar ruta;Propiedades;Historial de pestañas;Grupos;Deshacer cierre de pestaña;Ir a la última pestaña activada;Archivos abiertos recientemente;Buscar carpeta y abrir en pestaña;Cerrar todas menos la pestaña actual;Cerrar la ventana;Opciones;Desbloquear;Añadir al menú de la aplicación : ;elementos;Cancelar;Ramas;Eliminar este elemento d [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string TabBar_Menu {
        get {
            return ResourceManager.GetString("TabBar_Menu", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 QTTabBar ha fallado al abrir
    ///
    /// &quot;{0}&quot;. 的本地化字符串。
    /// </summary>
    internal static string TabBar_Message {
        get {
            return ResourceManager.GetString("TabBar_Message", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Crear nuevo grupo;Nombre del grupo:;Añadir todas las pestañas 的本地化字符串。
    /// </summary>
    internal static string TabBar_NewGroup {
        get {
            return ResourceManager.GetString("TabBar_NewGroup", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Ventana;Pestañas;Ajustes;Herramientas;General;Apariencia;Ratón;Teclado;Grupos;Aplicaciones;Barra de botones;Complementos;Idioma;Acerca de 的本地化字符串。
    /// </summary>
    internal static string TabBar_Option_Genre {
        get {
            return ResourceManager.GetString("TabBar_Option_Genre", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Barra de Tareas;Escritorio;Bloquear elementos;Dibujo del fondo del título;Menú con un solo clic;Habilitar las teclas de acceso directo a las aplicaciones 的本地化字符串。
    /// </summary>
    internal static string TaskBar_Menu {
        get {
            return ResourceManager.GetString("TaskBar_Menu", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Grupos;Deshacer el cierre;Aplicaciones;Archivos abiertos recientemente 的本地化字符串。
    /// </summary>
    internal static string TaskBar_Titles {
        get {
            return ResourceManager.GetString("TaskBar_Titles", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 1 ventana;{0} ventanas 的本地化字符串。
    /// </summary>
    internal static string TrayIcon {
        get {
            return ResourceManager.GetString("TrayIcon", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Se ha publicado una nueva versión de QTTabBar:;Pulse OK para ir a la página web.;Su versión de QTTabBar está actualizada.;Se ha encontrado una nueva versión de desarrollo:;Archivo de versión no encontrado (404).;Error de red desconocido.;Servidor no encontrado.;El servidor devolvió cadenas erróneas. 的本地化字符串。
    /// </summary>
    internal static string UpdateCheck {
        get {
            return ResourceManager.GetString("UpdateCheck", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 DevBuild: 2022/8/15 19:01:42 (2.0.50727.9164) 的本地化字符串。
    /// </summary>
    internal static string Version_QTTabBar {
        get {
            return ResourceManager.GetString("Version_QTTabBar", resourceCulture);
        }
    }
}
