//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9164
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   强类型资源类，用于查找本地化字符串等。
/// </summary>
// 此类是由 StronglyTypedResourceBuilder
// 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
// 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
// (以 /str 作为命令选项)，或重新生成 VS 项目。
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources_String_fr_FR {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources_String_fr_FR() {
    }
    
    /// <summary>
    ///   返回此类使用的缓存 ResourceManager 实例。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources_String_fr_FR", typeof(Resources_String_fr_FR).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   为使用此强类型资源类的所有资源查找
    ///   重写当前线程的 CurrentUICulture 属性。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   查找类似 SaiyajinK 的本地化字符串。
    /// </summary>
    internal static string Author {
        get {
            return ResourceManager.GetString("Author", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Séparateur;Retour;Avant;Groupes;Récemment fermé;Applications;Nouvelle fenêtre;Cloner ceci;Verouiller;Outil de copie;Le plus haut;Fermer;Fermer tout sauf courant;Fermer fenêtre;Fermer à gauche;Fermer à droite;Augmente d&apos;un niveau;Recharger;Recherche;Opacité;Barre de recherche;Options 的本地化字符串。
    /// </summary>
    internal static string ButtonBar_BtnName {
        get {
            return ResourceManager.GetString("ButtonBar_BtnName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Chemin;Nom;Chemin du dossier actuel;Nom du dossier actuel;MD5;éléments;Chemins de tous les onglets ouverts 的本地化字符串。
    /// </summary>
    internal static string ButtonBar_Misc {
        get {
            return ResourceManager.GetString("ButtonBar_Misc", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 France 的本地化字符串。
    /// </summary>
    internal static string Country {
        get {
            return ResourceManager.GetString("Country", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 08/15/2022 的本地化字符串。
    /// </summary>
    internal static string DateModified {
        get {
            return ResourceManager.GetString("DateModified", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Liste;Détails;Tuiles;Défaut 的本地化字符串。
    /// </summary>
    internal static string Desktop {
        get {
            return ResourceManager.GetString("Desktop", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 OK;Annuler;&amp;Appliquer;&amp;Défaut;Réinitialiser &amp;Page;&amp;Tout réinitialiser;Réinitialiser;Ajouter;Ajouter..;Supprimer;Options;Activer;Désactiver;Annuler;Charger...;Sauvegarder... 的本地化字符串。
    /// </summary>
    internal static string DialogButtons {
        get {
            return ResourceManager.GetString("DialogButtons", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Copier dans:;Déplacer dans:;Créer un raccourci dans: 的本地化字符串。
    /// </summary>
    internal static string DragDropToolTip {
        get {
            return ResourceManager.GetString("DragDropToolTip", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 L&apos;opération a échoué.
    ///Veuillez vous assurer que le fichier ou la cible du lien existe:
    ///
    ///{0};Erreur - QTTabBar;Avertissement: Impossible d&apos;activer automatiquement QTTabBar. Pour l&apos;activer manuellement, appuyez et relâchez la touche Alt, puis sélectionnez QTTabBar dans le menu Affichage/Barres d&apos;outils.;Impossible d&apos;activer;Erreur;Impossible de charger la bibliothèque de crochets QTTabBar.;Impossible d&apos;initialiser la bibliothèque de crochets QTTabBar.;Certaines fonctionnalités peuvent ne pas être fonctionn [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string ErrorDialogs {
        get {
            return ResourceManager.GetString("ErrorDialogs", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Fichiers images;Fichiers de langue;Fichiers Plugin 的本地化字符串。
    /// </summary>
    internal static string FileFilters {
        get {
            return ResourceManager.GetString("FileFilters", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Chemin;Hacher;Fermer;Effacer;Rafraîchir;Toujours au premier-plan;Afficher le résultat;Effacer à la fermeture;Chemin complet;(Calcul en cours...) 的本地化字符串。
    /// </summary>
    internal static string FileHashComputer {
        get {
            return ResourceManager.GetString("FileHashComputer", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 French 的本地化字符串。
    /// </summary>
    internal static string Language {
        get {
            return ResourceManager.GetString("Language", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Tout;Gauche;Haut;Droite;Bas 的本地化字符串。
    /// </summary>
    internal static string MarginDropDown {
        get {
            return ResourceManager.GetString("MarginDropDown", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Recherche bureau;Le fichier image n&apos;est pas valide.
    ///
    ///Veuillez préciser 432 x 40 px fichier d&apos;image.;Résultats de la recherche dans;Raccourci;Choisissez votre fichier;Choisissez votre dossier;Expérimental;dummy 的本地化字符串。
    /// </summary>
    internal static string Misc_Strings {
        get {
            return ResourceManager.GetString("Misc_Strings", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Modifiez le comportement de l&apos;explorateur Windows.;Mode de fenêtre unique;Capturez de nouvelles fenêtres de l&apos;explorateur sous forme de nouveaux onglets;Ne capturez pas les nouvelles fenêtres de l&apos;explorateur;Emplacement par défaut des nouvelles fenêtres et onglets;Enregistrement de session;Commencer une nouvelle session à chaque fois;Restaurer tous les onglets de la session précédente;Restaurer uniquement les onglets verrouillés de la session précédente;Lorsque le bouton de fermeture est pressé;Ferme la fe [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page01_Window {
        get {
            return ResourceManager.GetString("Options_Page01_Window", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Modifier les options liées aux onglets.;Ouvrir de nouveaux onglets :;Lorsque l&apos;onglet actuel est fermé, basculez vers:;Passez immédiatement aux nouveaux onglets;Réutiliser les onglets existants;Renommer les onglets ambigus;Lorsque vous faites glisser la souris sur un onglet,;Switcher;Afficher le sous-dossier du menu Astuce;Icônes d&apos;onglet;Afficher les icônes de dossier sur les onglets;Afficher le sous-dossier du menu Astuce lorsque l&apos;icône est cliquée;Afficher la lettre du lecteur sur l&apos;icône;Bouton Fermer; [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page02_Tabs {
        get {
            return ResourceManager.GetString("Options_Page02_Tabs", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Activez ou désactivez les modifications apportées à la vue de liste de l&apos;explorateur.;Tweaks pouvant être utilisés avec l&apos;une ou l&apos;autre des vues de liste;Afficher les en-têtes de colonne dans tous les modes d&apos;affichage (Windows Vista/7);Utiliser la vue standard du système de fichiers pour les dossiers de la bibliothèque (Windows 7);Désélectionnez l&apos;extension de fichier lorsque vous renommez des fichiers (Windows XP);Sélection du cycle avec F2 lors du changement de nom;Retour en boucle lors du déplacement d [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page03_Tweaks {
        get {
            return ResourceManager.GetString("Options_Page03_Tweaks", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Modifiez le comportement des info-bulles de sous-dossier et d&apos;aperçu.;Conseils sur les sous-dossiers;Activer les conseils de sous-dossier;Seulement avec la touche Maj enfoncée;Afficher les fichiers;Afficher les info-bulles d&apos;aperçu lorsque vous passez la souris sur les éléments de menu;Aperçu des info-bulles;Activer les info-bulles d&apos;aperçu;Seulement avec la touche Maj enfoncée;Afficher les informations du fichier sous les images;Largeur x Hauteur maximale:;Polcice:;Types de fichiers texte;Types de fichiers [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page04_Tooltips {
        get {
            return ResourceManager.GetString("Options_Page04_Tooltips", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Options générales pour le comportement de QTTabBar.;Intégration de la barre des tâches;Afficher les aperçus des onglets dans la barre des tâches;Historique;Conserver l&apos;historique des onglets fermés;Effacer maintenant;Conserver l&apos;historique des fichiers ouverts;Réseau;Délai d&apos;expiration du réseau (Entrez 0 pour la valeur par défaut du système):;Vérifiez périodiquement les mises à jour;Vérifier maintenant;Exporter;Exporter les paramètres...;Effacer l&apos;historique des fichiers ?;Effacer l&apos;historique des onglets  [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page05_General {
        get {
            return ResourceManager.GetString("Options_Page05_General", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Modifiez l&apos;apparence des onglets ou de la barre d&apos;onglets.;Image de l&apos;onglet;Utiliser une image de l&apos;onglet personnalisé:;Marges de dimensionnement:;Zone de chevauchement:;Marges de contenu:;Testez les zones transparentes;Taille de l&apos;onglet;Hauteur:;Largeur minimale:;Largeur maximale:;Mode mise à l&apos;échelle:;Pleine largeur;Même taille;Texte de l&apos;onglet;Couleurs du texte :;Couleurs de l&apos;ombre :;Couleur active;Couleur inactive;Couleur de la souris;Police de texte:;Alignement:;Gauche;Centrer;Arrière-plan de la  [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page06_Appearance {
        get {
            return ResourceManager.GetString("Options_Page06_Appearance", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Attribuez des commandes à différentes actions de la souris.;Pour ajouter un raccourci de souris, effectuez une action de la souris sur l&apos;icône plus à gauche du type de cible approprié. Pour supprimer une liaison, sélectionnez-la dans la liste et appuyez sur la touche Suppr.;Autres options de souris;La molette de la souris fait défiler la fenêtre sous la souris;Accord de souris;Action;Partout;Onglet;Arrière-plan de l&apos;onglet;Lien de dossier;Fichier ou dossier;Arrière-plan de l&apos;explorateur;Clique gauche;Clique [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page07_Mouse {
        get {
            return ResourceManager.GetString("Options_Page07_Mouse", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Modifier les raccourcis clavier.;Sélectionnez une action dans la liste et appuyez sur la touche gestuelle que vous souhaitez lui associer. Appuyez sur Échap pour effacer la liaison.;Autres options de clavier;Afficher la fenêtre de switch de l&apos;onglet lorsque Ctrl + Tab est enfoncé;Action;Frappe;Cette clé est déjà affectée à :;Doit-il être réaffecté ?;Conflit de frappe 的本地化字符串。
    /// </summary>
    internal static string Options_Page08_Keys {
        get {
            return ResourceManager.GetString("Options_Page08_Keys", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Créer et gérer des groupes d&apos;onglets.;Pour attribuer une touche de raccourci à un groupe, sélectionnez-la et appuyez sur le geste de touche approprié. Appuyez sur Échap pour effacer la liaison.;Créer un nouveau groupe;Dossier;Commencez;Touche de raccourci;Nouveau groupe;Ouvrir le groupe &quot;{0}&quot; 的本地化字符串。
    /// </summary>
    internal static string Options_Page09_Groups {
        get {
            return ResourceManager.GetString("Options_Page09_Groups", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Créez des raccourcis vers des fichiers ou des applications couramment utilisés.;Pour attribuer une touche de raccourci à une application, sélectionnez-la et appuyez sur le geste de touche approprié. Appuyez sur Échap pour effacer la liaison.;Créer un nouveau dossier;Chemin:;Arguments:;Répertoire de travail:;Application;Touche de raccourci;Les mots clés suivants sont remplacés avec le chemin des règles lors de l&apos;exécution.;Fichiers sélectionnés.;Dossiers sélectionnés.;Fichiers et dossiers sélectionnés.;Dossi [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page10_Apps {
        get {
            return ResourceManager.GetString("Options_Page10_Apps", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Personnalisez la barre de boutons.;Boutons;Options de la barre de boutons;Grandes icônes;Afficher les noms sur les boutons;Verrouiller l&apos;ordre des menus des boutons déroulants;Verrouiller la taille du champ de recherche;Images de boutons personnalisés 的本地化字符串。
    /// </summary>
    internal static string Options_Page11_ButtonBar {
        get {
            return ResourceManager.GetString("Options_Page11_ButtonBar", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Gérer les plugins tiers.;Installer un plugin;(Désactivé);par {0};{0} a été supprimé.;Ce plugin sera installé lorsque vous appuyez sur OK ou Appliquer.;Ce plugin sera activé lorsque vous appuyez sur OK ou Appliquer.;Ce plugin sera désactivé lorsque vous appuyez sur OK ou Appliquer.;La désinstallation de ce plugin désinstallera également les plugins suivants :;Procéder?;Activer;Désactiver 的本地化字符串。
    /// </summary>
    internal static string Options_Page12_Plugins {
        get {
            return ResourceManager.GetString("Options_Page12_Plugins", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Changez la langue.;Langage principal;Utiliser le langage intégré:;Utiliser le fichier de langue:;Fichiers de langue du plug-in;Éditeur de fichiers de langue;Afficher l&apos;éditeur de langue...;Original;Traduit;Réinitialiser toutes les entrées à leur valeur d&apos;origine ?;Erreur lors de l&apos;enregistrement du fichier.;Chinois simplifié;Anglais;Allemand 的本地化字符串。
    /// </summary>
    internal static string Options_Page13_Language {
        get {
            return ResourceManager.GetString("Options_Page13_Language", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Afficher les crédits et les informations de version.;Code d&apos;origine de {0};Développeur principal:;Autres développeurs:;Icônes et graphiques:;Si vous trouvez QTTabBar utile, pensez à faire un petit don.;Modification chinoise:;Construit par : {0} 的本地化字符串。
    /// </summary>
    internal static string Options_Page14_About {
        get {
            return ResourceManager.GetString("Options_Page14_About", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Options de QTTabBar;Réinitialiser toutes les options de cette page à leurs valeurs par défaut ?;Réinitialiser toutes les options à leurs valeurs par défaut ? Cela n&apos;affectera pas les groupes, les applications ou les plugins.;Confirmation 的本地化字符串。
    /// </summary>
    internal static string OptionsDialog {
        get {
            return ResourceManager.GetString("OptionsDialog", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 https://github.com/indiff/qttabbar/blob/master/QTTabBar/Resources/wechat_pay.jpg 的本地化字符串。
    /// </summary>
    internal static string PayPalURL {
        get {
            return ResourceManager.GetString("PayPalURL", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Retour;Avant;Aller en arrière pour commencer;Aller en avant pour finir;Sélectionnez l&apos;onglet suivant;Sélectionner l&apos;onglet précédent;Sélectionnez le premier onglet;Select last tab;Sélectionner le dernier onglet;Ouvrir un nouvel onglet;Ouvrir une nouvelle fenêtre;Fusionner les onglets d&apos;autres fenêtres;Fermer l&apos;onglet actuel;Fermer tout sauf courant;Fermer à gauche;Fermer à droite;Fermer la fenêtre;Annuler fermeture;Cloner l&apos;onglet actuel;Ouvrir le dossier actuel dans une nouvelle fenêtre;Verrouiller / déver [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string ShortcutKeys_ActionNames {
        get {
            return ResourceManager.GetString("ShortcutKeys_ActionNames", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 QTTabBar;{0} (Plugin) 的本地化字符串。
    /// </summary>
    internal static string ShortcutKeys_Groups {
        get {
            return ResourceManager.GetString("ShortcutKeys_Groups", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 https://github.com/indiff/qttabbar 的本地化字符串。
    /// </summary>
    internal static string SiteURL {
        get {
            return ResourceManager.GetString("SiteURL", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Fermer;Fermer à droite;Fermer à gauche;Fermer tout sauf ça;Ajouter au groupe;Créer un nouveau groupe;Verrouiller;Cloner ceci;Nouvelle fenetre;Copier le chemin;Propriétés;Historique des onglets;Groupes;Annuler fermeture;Dernière activation;Fichiers récemment ouverts;Parcourir le dossier;Fermer tout sauf courant;Fermer la fenêtre;Options;Déverouiller;Ajouter au menu de l&apos;application :;éléments;Annuler;Branches;Supprimer cet élément du menu;Ouvrir dossier contenant;Nom de l&apos;onglet;Ordre de l&apos;onglet;Nom;Chemin; [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string TabBar_Menu {
        get {
            return ResourceManager.GetString("TabBar_Menu", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 QTTabBar n&apos;a pas pu s&apos;ouvrir
    ///
    /// &quot;{0}&quot;. 的本地化字符串。
    /// </summary>
    internal static string TabBar_Message {
        get {
            return ResourceManager.GetString("TabBar_Message", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Créer un nouveau groupe;Nom groupe:;Ajouter tous les onglets 的本地化字符串。
    /// </summary>
    internal static string TabBar_NewGroup {
        get {
            return ResourceManager.GetString("TabBar_NewGroup", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Fenêtre;Onglets;Tweaks;Info-bulles;Général;Apparence;Souris;Raccourcis;Groupes;Applications;Barre de boutons;Plugins;Langue;À propos 的本地化字符串。
    /// </summary>
    internal static string TabBar_Option_Genre {
        get {
            return ResourceManager.GetString("TabBar_Option_Genre", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Barre des tâches;Bureau;Verrouiller les éléments;Dessiner l&apos;arrière-plan du titre;Menu en un clic;Activer les touches de raccourci d&apos;application 的本地化字符串。
    /// </summary>
    internal static string TaskBar_Menu {
        get {
            return ResourceManager.GetString("TaskBar_Menu", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Groupes;Annuler fermeture;Applications;Fichiers récemment ouverts 的本地化字符串。
    /// </summary>
    internal static string TaskBar_Titles {
        get {
            return ResourceManager.GetString("TaskBar_Titles", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 1 fenêtre;{0} fenêtre 的本地化字符串。
    /// </summary>
    internal static string TrayIcon {
        get {
            return ResourceManager.GetString("TrayIcon", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Une nouvelle version de QTTabBar est disponible:;Appuyez sur OK pour accéder au site Web.;Votre version de QTTabBar est à jour.;Nouvelle version de développement trouvée:;Fichier de version introuvable (404).;Erreur réseau inconnue.;Serveur introuvable.;Le serveur a renvoyé des erreurs 的本地化字符串。
    /// </summary>
    internal static string UpdateCheck {
        get {
            return ResourceManager.GetString("UpdateCheck", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 DevBuild: 2022/8/15 19:01:42 (2.0.50727.9164) 的本地化字符串。
    /// </summary>
    internal static string Version_QTTabBar {
        get {
            return ResourceManager.GetString("Version_QTTabBar", resourceCulture);
        }
    }
}
