//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTTabBarLib {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_String() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QTTabBarLib.Resources_String", typeof(Resources_String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Separator;Go back;Go forward;Groups;Recently Closed;Applications;New window;Clone this;Lock;Copy Tool;TopMost;Close;Close all but current;Close window;Close left;Close right;Up one level;Reload;Search;Opacity;Search Box;Options 的本地化字符串。
        /// </summary>
        public static string ButtonBar_BtnName {
            get {
                return ResourceManager.GetString("ButtonBar_BtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path;Name;Current folder path;Current folder name;MD5; items;Paths of all open tabs 的本地化字符串。
        /// </summary>
        public static string ButtonBar_Misc {
            get {
                return ResourceManager.GetString("ButtonBar_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List;Details;Tiles;Default 的本地化字符串。
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK;Cancel;&amp;Apply;&amp;Default;Reset &amp;Page;&amp;Reset All;Reset;Add;Add...;Remove;Options;Enable;Disable;Undo;Load...;Save... 的本地化字符串。
        /// </summary>
        public static string DialogButtons {
            get {
                return ResourceManager.GetString("DialogButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy to:;Move to:;Create shortcut in: 的本地化字符串。
        /// </summary>
        public static string DragDropToolTip {
            get {
                return ResourceManager.GetString("DragDropToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation failed.\r\nPlease make sure the file or the target of link exists:\r\n\r\n{0};Error - QTTabBar;Warning:  Could not automatically enable QTTabBar. To enable it manually, press and release the Alt key, then select QTTabBar from the View/Toolbars menu.;Could not enable;Error;Unable to load QTTabBar hook library.;Unable to initialize QTTabBar hook library.;Some features might not be functional. To resolve this, you may need to reinstall the application.;Failed to hook Desktop. Please re-enable QT Tab  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ErrorDialogs {
            get {
                return ResourceManager.GetString("ErrorDialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Files;Language Files;Plugin Files 的本地化字符串。
        /// </summary>
        public static string FileFilters {
            get {
                return ResourceManager.GetString("FileFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path;Hash;Close;Clear;Refresh;Always on top;Show result;Clear on close;Full path;(Now calculating...) 的本地化字符串。
        /// </summary>
        public static string FileHashComputer {
            get {
                return ResourceManager.GetString("FileHashComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All;Left;Top;Right;Bottom 的本地化字符串。
        /// </summary>
        public static string MarginDropDown {
            get {
                return ResourceManager.GetString("MarginDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desktop Search;Image file is invalid.\r\n\r\nPlease specify 432 x 40 px image file.;Search Results in;shortcut;Choose your file;Choose your folder;Experimental;dummy 的本地化字符串。
        /// </summary>
        public static string Misc_Strings {
            get {
                return ResourceManager.GetString("Misc_Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change how Explorer Windows behave.;Single Window mode;Capture new Explorer windows as new tabs;Do not capture new Explorer windows;Default location for new windows and tabs;Session saving;Start a new session each time;Restore all tabs from the previous session;Restore only the locked tabs from the previous session;When the close button is clicked;Close the window;Close the current tab;Close all unlocked tabs;Send the window to the Task Tray on;Close;Minimize;Blue Plus Button 的本地化字符串。
        /// </summary>
        public static string Options_Page01_Window {
            get {
                return ResourceManager.GetString("Options_Page01_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change options related to tabs.;Open new tabs:;When the current tab is closed, switch to the:;Switch to new tabs immediately;Reuse existing tabs;Rename ambiguous tabs;When drag-hovering over a tab,;Switch to it;Show the Subfolder Tip menu;Tab icons;Show folder icons on tabs;Show the Subfolder Tip menu when the icon is clicked;Show the drive letter on the icon;Close button;Show close button on tabs;Only with the Alt key down;Only on mouse hover;Tab Bar;Show navigation buttons on the tab bar;On the left;On th [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Options_Page02_Tabs {
            get {
                return ResourceManager.GetString("Options_Page02_Tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable or disable tweaks to Explorer&apos;s List View.;Tweaks that can be used with either List View;Display column headers in all view modes (Windows Vista/7);Use the standard filesystem view for Library folders (Windows 7);Deselect file extension when renaming files (Windows XP);Cycle selection with F2 while renaming;Wrap around when moving the selection with the arrow keys;Backspace goes up one level (Windows Vista/7);Scrolling with mouse wheel while holding shift scrolls horizontally;Tweaks that can only be  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Options_Page03_Tweaks {
            get {
                return ResourceManager.GetString("Options_Page03_Tweaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change the behavior of Subfolder and Preview tooltips.;Subfolder Tips;Enable Subfolder Tips;Only with the Shift key is down;Show files;Show preview tooltips when mousing over menu items;Preview tooltips;Enable preview tooltips;Only with the Shift key is down;Show file information below images;Maximum Width x Height:;Font:;Text filetypes;Image and Video filetypes 的本地化字符串。
        /// </summary>
        public static string Options_Page04_Tooltips {
            get {
                return ResourceManager.GetString("Options_Page04_Tooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General options for QTTabBar&apos;s behavoir.;Taskbar integration;Show tab previews on the Taskbar;History;Keep history of closed tabs;Clear now;Keep history of opened files;Network;Network timeout (Enter 0 for system default):;Check for updates periodically;Check now;Export;Export Settings...;Clear file history?;Clear tab history? 的本地化字符串。
        /// </summary>
        public static string Options_Page05_General {
            get {
                return ResourceManager.GetString("Options_Page05_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change the appearance of tabs or the tab bar.;Tab image;Use custom tab image:;Sizing margins:;Overlap area:;Content margins:;Hit test transparent areas;Tab size;Height:;Min Width:;Max Width:;Sizing mode:;Full width;Same size;Tab text;Text Colors:;Shadow Colors:;Active Color;Inactive Color;Mouseover Color;Text Font:;Alignment:;Left;Center;Toolbar Background;Image;Solid color;Image each bar separately;Stretch mode:;Sizing margins:;Skin file;Import Skin...;Export Skin...;Stretch;True size;Tile 的本地化字符串。
        /// </summary>
        public static string Options_Page06_Appearance {
            get {
                return ResourceManager.GetString("Options_Page06_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assign commands to different mouse actions.;To add a mouse binding, perform a mouse action on the plus icon to the left of the appropriate target type.  To remove a binding, select it in the list and press the Delete key.;Other mouse options;Mouse wheel scrolls the window under the mouse;Mouse Chord;Action;Anywhere;Tab;Tab Bar Background;Folder Link;File or Folder;Explorer Background;Left Click;Right Click;Middle Click;Double Click;X1 Click;X2 Click;This mouse button cannot be used for this target.;The vali [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Options_Page07_Mouse {
            get {
                return ResourceManager.GetString("Options_Page07_Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change keyboard shortcuts.;Select an action from the list and press the key gesture you would like to bind to it.  Press Escape to clear the binding.;Other keyboard options;Show the Tab Switcher window when Ctrl + Tab is pressed;Action;Keystroke;This key is already assigned to:;Should it be reassigned?;Keystroke conflict 的本地化字符串。
        /// </summary>
        public static string Options_Page08_Keys {
            get {
                return ResourceManager.GetString("Options_Page08_Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create and manage tab groups.;To assign a Shortcut Key to a group, select it and press the appropriate key gesture.  Press Escape to clear the binding.;Create New Group;Folder;Startup;Shortcut Key;New Group;Open group &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        public static string Options_Page09_Groups {
            get {
                return ResourceManager.GetString("Options_Page09_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create shortcuts to commonly used files or applications.;To assign a Shortcut Key to an application, select it and press the appropriate key gesture.  Press Escape to clear the binding.;Create New Folder;Path:;Arguments:;Working Directory:;Application;Shortcut Key;The following keywords are replaced with double-quoted path strings at runtime.;Selected files.;Selected folders.;Selected files and folders.;Current folder.;Current folder if no selection, otherwise selected folder.;New Folder;Remove this folder  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Options_Page10_Apps {
            get {
                return ResourceManager.GetString("Options_Page10_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize the Button Bar.;Buttons;Button Bar Options;Large icons;Show labels on buttons;Lock the order of dropdown button menus;Lock the size of the search box;Custom Button Images 的本地化字符串。
        /// </summary>
        public static string Options_Page11_ButtonBar {
            get {
                return ResourceManager.GetString("Options_Page11_ButtonBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage third-party plugins.;Install a Plugin;(Disabled);by {0};{0} has been removed.;This plugin will be installed when you press OK or Apply.;This plugin will be enabled when you press OK or Apply.;This plugin will be disabled when you press OK or Apply.;Uninstalling this plugin will also uninstall the following plugins:;Proceed?;Enable;Disable 的本地化字符串。
        /// </summary>
        public static string Options_Page12_Plugins {
            get {
                return ResourceManager.GetString("Options_Page12_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change the language.;Main language;Use built-in language:;Use language file:;Plugin language files;Language File Editor;Show Language Editor...;Original;Translated;Reset all entries to their original value?;Error saving file.;简体中文 的本地化字符串。
        /// </summary>
        public static string Options_Page13_Language {
            get {
                return ResourceManager.GetString("Options_Page13_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View credits and version information.;Original code by {0};Lead Developer:;Other Developers:;Icons and graphics:;If you find QTTabBar useful, please consider making a small donation.;汉化修改：;Build by: {0} 的本地化字符串。
        /// </summary>
        public static string Options_Page14_About {
            get {
                return ResourceManager.GetString("Options_Page14_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QTTabBar Options;Reset all options on this page to their default values?;Reset all options to their default values?  This will not affect Groups, Applications, or Plugins.;Confirmation 的本地化字符串。
        /// </summary>
        public static string OptionsDialog {
            get {
                return ResourceManager.GetString("OptionsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/indiff/qttabbar/blob/master/QTTabBar/Resources/wechat_pay.jpg 的本地化字符串。
        /// </summary>
        public static string PayPalURL {
            get {
                return ResourceManager.GetString("PayPalURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go back;Go forward;Go back to start;Go forward to end;Select next tab;Select previous tab;Select first tab;Select last tab;Switch to last activated tab;Open new tab;Open new window;Merge tabs from other windows;Close current tab;Close all but current;Close left;Close right;Close window;Undo close;Clone current tab;Open current folder in new window;Lock / unlock current;Lock / unlock all;Browse folder;Create new group;Open option dialog;Show toolbar menu;Show current tab menu;Show group menu (Button Bar);Sho [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ShortcutKeys_ActionNames {
            get {
                return ResourceManager.GetString("ShortcutKeys_ActionNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QTTabBar;{0} (Plugin) 的本地化字符串。
        /// </summary>
        public static string ShortcutKeys_Groups {
            get {
                return ResourceManager.GetString("ShortcutKeys_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/indiff/qttabbar 的本地化字符串。
        /// </summary>
        public static string SiteURL {
            get {
                return ResourceManager.GetString("SiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close;Close right;Close left;Close all but this;Add to Group;Create new Group;Lock;Clone this;New window;Copy path;Properties;Tab history;Groups;Undo closed;Last activated;Recently opened files;Browse folder;Close all but current;Close Window;Options;Unlock;Add to Application menu : ;items;Cancel;Branches;Remove this item from menu;O&amp;pen containing folder;Tab label;Tab order;Name;Path;Active;Lock the Toolbars;Merge tabs of other windows;Invert;Open CMD 的本地化字符串。
        /// </summary>
        public static string TabBar_Menu {
            get {
                return ResourceManager.GetString("TabBar_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QTTabBar failed to open
        ///
        /// &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        public static string TabBar_Message {
            get {
                return ResourceManager.GetString("TabBar_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create New Group;Group name:;Add all tabs 的本地化字符串。
        /// </summary>
        public static string TabBar_NewGroup {
            get {
                return ResourceManager.GetString("TabBar_NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window;Tabs;Tweaks;Tooltips;General;Appearance;Mouse;Keys;Groups;Applications;Button Bar;Plugins;Language;About 的本地化字符串。
        /// </summary>
        public static string TabBar_Option_Genre {
            get {
                return ResourceManager.GetString("TabBar_Option_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Taskbar;Desktop;Lock items;Draw title background;Menu by one click;Enable application shortcut keys 的本地化字符串。
        /// </summary>
        public static string TaskBar_Menu {
            get {
                return ResourceManager.GetString("TaskBar_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Groups;Undo closed;Applications;Recently opened files 的本地化字符串。
        /// </summary>
        public static string TaskBar_Titles {
            get {
                return ResourceManager.GetString("TaskBar_Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 window;{0} windows 的本地化字符串。
        /// </summary>
        public static string TrayIcon {
            get {
                return ResourceManager.GetString("TrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A new version of QTTabBar has been released:;Press OK to go to the web site.;Your version of QTTabBar is up to date.;New development version found:;Version file not found (404).;Unknown network error.;Server not found.;Server returned wrong strings. 的本地化字符串。
        /// </summary>
        public static string UpdateCheck {
            get {
                return ResourceManager.GetString("UpdateCheck", resourceCulture);
            }
        }
    }
}
