//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTTabBarLib {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_String_zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_String_zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QTTabBarLib.Resource_String_zh_CN", typeof(Resource_String_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 分隔线;后退;前进;标签组;最近关闭标签;应用程序;新窗口;复制标签;锁定;复制工具;顶层显示;关标签;关其他;关窗口;关左侧;关右侧;上移;重载;搜索;半透明;搜索框;选项 的本地化字符串。
        /// </summary>
        internal static string ButtonBar_BtnName {
            get {
                return ResourceManager.GetString("ButtonBar_BtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径;名称;当前文件夹路径;当前文件夹名称;MD5; 个项目;所有打开的标签路径 的本地化字符串。
        /// </summary>
        internal static string ButtonBar_Misc {
            get {
                return ResourceManager.GetString("ButtonBar_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表;详细;平铺;默认 的本地化字符串。
        /// </summary>
        internal static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定;取消;应用(&amp;A);默认值(&amp;D);重置&amp;该页;&amp;重置所有;重置;添加;添加...;删除;选项;启用;禁用;撤销;加载...;保存... 的本地化字符串。
        /// </summary>
        internal static string DialogButtons {
            get {
                return ResourceManager.GetString("DialogButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制到：;移到：;建立快捷方式到： 的本地化字符串。
        /// </summary>
        internal static string DragDropToolTip {
            get {
                return ResourceManager.GetString("DragDropToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败\r\n请确保存在的文件或链接目标：\r\n\r\n{0};错误 - QTTabBar;警告：无法自动启用QTTabBar。若要启用手动，按下并松开Alt键，然后选择“视图/工具栏菜单QTTabBar。;无法启用;错误;无法加载QTTabBar的hook库;无法初始化QTTabBar的hook库.;有些功能可能无法发挥作用。为了解决这个问题，你可能需要重新安装应用程序。;无法挂钩桌面。请重新启用QT标签桌面工具。;操作失败\r\n请确保该文件夹存在，或者您有权限访问：\r\n\r\n\t{0} 的本地化字符串。
        /// </summary>
        internal static string ErrorDialogs {
            get {
                return ResourceManager.GetString("ErrorDialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片文件;语言文件;插件文件 的本地化字符串。
        /// </summary>
        internal static string FileFilters {
            get {
                return ResourceManager.GetString("FileFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径;哈希;关闭;清除;刷新;总在最前;显示结果;关闭清除;全路径;(正在计算...) 的本地化字符串。
        /// </summary>
        internal static string FileHashComputer {
            get {
                return ResourceManager.GetString("FileHashComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有;左;上;右;底 的本地化字符串。
        /// </summary>
        internal static string MarginDropDown {
            get {
                return ResourceManager.GetString("MarginDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌面搜索;无效的图片。\r\n\r\n请选择 432 x 40 px 的图片。;搜索结果在;快捷方式;选择你的文件;选择你的文件夹;实验性的;仿制 的本地化字符串。
        /// </summary>
        internal static string Misc_Strings {
            get {
                return ResourceManager.GetString("Misc_Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源管理器窗口模式及会话.;单窗口模式;捕捉新Explorer窗口为标签;不捕捉新Explorer窗口;新窗口和标签默认位置;会话保存;每次启动一个新会话;恢复上一个会话所有标签;只恢复上次会话锁定的标签;当关闭按钮被单击;关闭窗口;关闭当前标签;关闭所有未锁定标签;将窗口缩小到系统托盘;关闭;最小化;蓝色新增标签按钮 的本地化字符串。
        /// </summary>
        internal static string Options_Page01_Window {
            get {
                return ResourceManager.GetString("Options_Page01_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改标签的相关选项.;打开新标签:;当关闭当前标签，切换到：;立即切换到新标签;重用现有标签;模糊重命名标签;当拖拽到标签;切换到它;显示该子文件夹提示菜单;标签图标;在标签上显示文件夹图标;显示该子文件夹提示菜单点击该图标;显示驱动器的图标;关闭按钮;标签上显示关闭按钮;仅Alt键按下;仅鼠标悬停;标签栏;标签栏上显示导航按钮;在左边;在右边;允许多行标签;始终把将行活动标签置于底部;当前标签左侧;当前标签右侧;最左侧;最右侧;标签左侧;标签右侧;标签最左侧;标签最右侧;最后激活标签;行为 的本地化字符串。
        /// </summary>
        internal static string Options_Page02_Tabs {
            get {
                return ResourceManager.GetString("Options_Page02_Tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用或禁用调整Explorer的列表视图。;【微调/Tweaks】可以使用任一列表视图的调整;显示列标题，在所有视图模式（Windows Vista中/ 7）;使用库文件夹（Windows 7中的标准文件系统视图）;启用当重命名文件不选择扩展名（Windows XP）;禁用F2重命名周期选择;当使用箭头键选择文件时候，环绕选择;Backspace键回到上一级目录（Windows Vista/7）;同时按住Shift鼠标滚轮水平滚动;微调适用于旧版列表视图;启用旧版列表视图控件（Windows 7）;在详细信息视图中的整行选中目标（Windows XP）;在详细信息视图中显示网格线;查看详细的交替行颜色;前景色：;背景色： 的本地化字符串。
        /// </summary>
        internal static string Options_Page03_Tweaks {
            get {
                return ResourceManager.GetString("Options_Page03_Tweaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改子目录行为和文件预览;子目录行为;启用&quot;子目录提示&quot;;仅当Shift键按下;显示包含文件;鼠标在菜单项时，启用文件预览;文件预览;启用文件预览;仅当Shift键按下;下面的图像中显示的文件信息;最大宽度x高度：;字体设置：;文本文件类型;图像和视频文件类型 的本地化字符串。
        /// </summary>
        internal static string Options_Page04_Tooltips {
            get {
                return ResourceManager.GetString("Options_Page04_Tooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QTTabBar常规选项;任务栏整合;任务栏显示标签预览;历史;保持关闭标签的历史;立即清除;保持打开文件的历史;网络;网络超时（系统默认输入为0）：;定期检查更新;现在检查;导出;导出设置...;清除文​​件历史？;清除历史标签？;声音;是否启用声音提示;是否启用日志功能 的本地化字符串。
        /// </summary>
        internal static string Options_Page05_General {
            get {
                return ResourceManager.GetString("Options_Page05_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改标签和标签栏的外观;标签背景;自定义图片：;设置边缘：;重叠区：;内容边缘：;命中测试透明区域;标签大小;高度：;最小宽度：;最大宽度：;宽度模式：;全宽;同样大小;标签文本;文字颜色：;阴影颜色：;激活的颜色;无效的颜色;鼠标悬停颜色;文本字体：;对齐方式：;居左;居中;工具栏背景;自定义图片;填充颜色;图片按每个工具栏区域填充;图片位置：;设置边缘：;皮肤文件;导入皮肤...;导出皮肤...;拉伸;适应;平铺 的本地化字符串。
        /// </summary>
        internal static string Options_Page06_Appearance {
            get {
                return ResourceManager.GetString("Options_Page06_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配到不同的鼠标操作的命令。;在左侧加号图标目标类型点击左键绑定合适的鼠标动作。若要删除绑定，在列表中选择它，然后按Delete键。;其他鼠标选项;滚动鼠标滚轮的鼠标下的窗口;目标和鼠标动作;对应的执行行为;任何地方;标签;标签栏空白处;文件夹链接;文件或文件夹;资源管理器空白处;左键;右键点击;中击;双击;X1的点击;X2的点击;您的鼠标动作无法适用于该目标。;该目标有效地鼠标操作为：;无效的鼠标动作 的本地化字符串。
        /// </summary>
        internal static string Options_Page07_Mouse {
            get {
                return ResourceManager.GetString("Options_Page07_Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改键盘快捷键。;从列表中选中一个动作，然后按键设置你想绑定的快捷键。按Escape清除绑定的快捷键。;其他键盘选项;显示标签切换窗口时，按下CTRL + TAB;执行动作;绑定快捷键;此键已分配给：;它应该被重新分配吗？;按键冲突 的本地化字符串。
        /// </summary>
        internal static string Options_Page08_Keys {
            get {
                return ResourceManager.GetString("Options_Page08_Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建和管理标签组。;从列表中选中一个分组，然后按键设置你想绑定的快捷键。按Escape清除绑定的快捷键。;创建新组;文件夹;是否启动;绑定快捷键;新的组;打开组“{0}” 的本地化字符串。
        /// </summary>
        internal static string Options_Page09_Groups {
            get {
                return ResourceManager.GetString("Options_Page09_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建常用的文件或应用程序的快捷方式。;从列表中选中一个快捷方式，然后按键设置你想绑定的快捷键。按Escape清除绑定的快捷键。;创建新文件夹;路径：;参数：;工作目录：;应用;快捷键;以下关键字在运行时会被替换为双引号路径字符串。;选定的文件。;选定的文件夹。;选定的文件和文件夹。;当前文件夹。;当前文件夹，如果没有选择，否则选定的文件夹。;新建文件夹;删除此文件夹及其内容？;启动应用程序“{0}” 的本地化字符串。
        /// </summary>
        internal static string Options_Page10_Apps {
            get {
                return ResourceManager.GetString("Options_Page10_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义按钮栏。;按钮;按钮栏选项;大图标;显示按钮上的标签;锁定的下拉按钮菜单的顺序;锁定搜索框的大小;自定义按钮图像 的本地化字符串。
        /// </summary>
        internal static string Options_Page11_ButtonBar {
            get {
                return ResourceManager.GetString("Options_Page11_ButtonBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理第三方插件。;安装插件;（禁用）;{0};{0}已被删除。;将要安装这个插件，当你按确定或应用。;将启用这个插件，当你按确定或应用。;这个插件将被禁止，当你按确定或应用。;卸载这个插件也将解除安装以下插件：;继续吗？;一键启用;一键禁用 的本地化字符串。
        /// </summary>
        internal static string Options_Page12_Plugins {
            get {
                return ResourceManager.GetString("Options_Page12_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改变语言。;主体语言;使用内置的语言：;使用语言文件：;插件语言文件;语言文件编辑器;显示语言编辑器...;原;翻译;其原始值重置所有条目？;保存文件时发生错误。;简体中文;英文;德语 的本地化字符串。
        /// </summary>
        internal static string Options_Page13_Language {
            get {
                return ResourceManager.GetString("Options_Page13_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看相关人员以及版本信息.;源代码 {0};主要开发人员：;其他开发人员：;图标和图形设计：;如果您发现QTTabBar有用，请考虑做一个小的捐赠。;汉化修改：;编译：{0} 的本地化字符串。
        /// </summary>
        internal static string Options_Page14_About {
            get {
                return ResourceManager.GetString("Options_Page14_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QTTabBar选项;重置此页面上的所有选项，其默认值？;所有选项重置为其默认值吗？这不会影响组，应用程序或插件。;确认 的本地化字符串。
        /// </summary>
        internal static string OptionsDialog {
            get {
                return ResourceManager.GetString("OptionsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/indiff/qttabbar/blob/master/QTTabBar/Resources/wechat_pay.jpg 的本地化字符串。
        /// </summary>
        internal static string PayPalURL {
            get {
                return ResourceManager.GetString("PayPalURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 ( Alt + Left );下一页 ( Alt + Right );首页;尾页;选择下一个标签;选择上一个标签;选择第一个标签;选择最后一个标签;切换到最后一个标签;新标签;新窗口;从其他窗口合并标签;关闭当前标签;关闭其他;关闭左标签;关闭右标签;关闭窗口;恢复关闭的标签;复制当前标签;以新窗口开启当前文件夹;锁定/解除锁定当前标签;锁定/解除锁定全部标签;浏览文件夹;建立新标签组;开启选项对话框;显示工具栏菜单;显示当前标签菜单;显示标签组菜单 ( 按钮栏 );显示最近文件夹菜单 ( 按钮栏 );显示使用者应用程序菜单 ( 按钮栏 );显示最近文件菜单 ( 按钮栏 );创建空文件;创建文件夹;复制所选文件路径;复制所选文件名称;复制当前文件夹路径;复制当前文件夹名称;检查所选文件的MD5;将窗口移至最上层;增加透明度;减少透明度;焦点移到文件列表;焦点移到搜索列 (Vista/Win7);焦点移到搜索框 ( 按钮栏 );显示所选文件夹的子目录提示菜单;将窗口缩小到系统托盘;焦点移到标签栏;按标签名称排序;按标签路径排序;按标签最后访问排序;无;上一级;刷新;粘贴;最大化;最小化;在新标签（激活标 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ShortcutKeys_ActionNames {
            get {
                return ResourceManager.GetString("ShortcutKeys_ActionNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QTTabBar;外挂插件;用户指令 的本地化字符串。
        /// </summary>
        internal static string ShortcutKeys_Groups {
            get {
                return ResourceManager.GetString("ShortcutKeys_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/indiff/qttabbar 的本地化字符串。
        /// </summary>
        internal static string SiteURL {
            get {
                return ResourceManager.GetString("SiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭;关闭右侧;关闭左侧;关闭其他标签;新增到标签组;建立新标签组;锁定;复制此标签;开新窗口;复制路径;属性;标签历史;标签组;复原关闭的标签;上次使用的标签;最近开启的文件;浏览文件夹;关闭其他标签;关闭窗口;选项;解除锁定;新增到应用程序菜单(&amp;A)：;个项目;取消;分支;从菜单移除此项;开启所在文件夹(&amp;P);标签标记;标签排序;名称;路径;使用中;锁定工具栏;合并其他窗口的标签;反向;打开命令提示符 的本地化字符串。
        /// </summary>
        internal static string TabBar_Menu {
            get {
                return ResourceManager.GetString("TabBar_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QTTabBar 无法打开 &quot;{0}&quot;。 的本地化字符串。
        /// </summary>
        internal static string TabBar_Message {
            get {
                return ResourceManager.GetString("TabBar_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建立新标签组;标签组名称：;加入所有标签 的本地化字符串。
        /// </summary>
        internal static string TabBar_NewGroup {
            get {
                return ResourceManager.GetString("TabBar_NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口行为;标签行为;调整工具;预览提示;常规选项;标签外观;鼠标操作;快捷操作;分组操作;自定应用;按钮选项;插件管理;语言配置;关于信息 的本地化字符串。
        /// </summary>
        internal static string TabBar_Option_Genre {
            get {
                return ResourceManager.GetString("TabBar_Option_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务栏(&amp;T);桌面(&amp;D);锁定项目(&amp;L);显示标题背景(&amp;B);单击显示菜单(&amp;O);启用程序快捷键(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string TaskBar_Menu {
            get {
                return ResourceManager.GetString("TaskBar_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签组;恢复关闭的标签;应用程序;最近的文件 的本地化字符串。
        /// </summary>
        internal static string TaskBar_Titles {
            get {
                return ResourceManager.GetString("TaskBar_Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个窗口;{0}窗口 的本地化字符串。
        /// </summary>
        internal static string TrayIcon {
            get {
                return ResourceManager.GetString("TrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个新版本QTTabBar已发布:;击打确定到站点.;你的QTTabBar版本是最新的.;发现新的开发版本:;版本文件未找到 (404).;未知的网络错误.;未发现服务器.;服务器返回错误信息. 的本地化字符串。
        /// </summary>
        internal static string UpdateCheck {
            get {
                return ResourceManager.GetString("UpdateCheck", resourceCulture);
            }
        }
    }
}
