//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9164
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   强类型资源类，用于查找本地化字符串等。
/// </summary>
// 此类是由 StronglyTypedResourceBuilder
// 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
// 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
// (以 /str 作为命令选项)，或重新生成 VS 项目。
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources_String_pt_BR {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources_String_pt_BR() {
    }
    
    /// <summary>
    ///   返回此类使用的缓存 ResourceManager 实例。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources_String_pt_BR", typeof(Resources_String_pt_BR).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   为使用此强类型资源类的所有资源查找
    ///   重写当前线程的 CurrentUICulture 属性。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   查找类似 JNylson 的本地化字符串。
    /// </summary>
    internal static string Author {
        get {
            return ResourceManager.GetString("Author", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Separador;Voltar;Avançar;Grupo;Recentes;Aplicativos;Nova janela;Fechar essa;Bloquear;Copiar;Sempre visível;Fechar;Fechar outras;Fechar janela;Fechar a esquerda;Fechar a direita;Subir um nível;Recarregar;Procurar;Opacidade;Caixa de pesquisa;Opções 的本地化字符串。
    /// </summary>
    internal static string ButtonBar_BtnName {
        get {
            return ResourceManager.GetString("ButtonBar_BtnName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Caminho;Nome;Caminho atual da pasta;Nome da pasta atual;MD5; itens;Caminhos de todas as abas abertas 的本地化字符串。
    /// </summary>
    internal static string ButtonBar_Misc {
        get {
            return ResourceManager.GetString("ButtonBar_Misc", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Brazil 的本地化字符串。
    /// </summary>
    internal static string Country {
        get {
            return ResourceManager.GetString("Country", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 08/15/2022 的本地化字符串。
    /// </summary>
    internal static string DateModified {
        get {
            return ResourceManager.GetString("DateModified", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Lista;Detalhes;Lado a lado;Padrão 的本地化字符串。
    /// </summary>
    internal static string Desktop {
        get {
            return ResourceManager.GetString("Desktop", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 OK;Cancelar;&amp;Aplicar;Pa&amp;drão;Resetar &amp;Página;&amp;Resetar Todos;Resetar;Adicionar;Adicionar...;Remover;Opções;Ativar;Desativar;Desfazer;Carregar...;Salvar... 的本地化字符串。
    /// </summary>
    internal static string DialogButtons {
        get {
            return ResourceManager.GetString("DialogButtons", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Copiar para:;Mover para:;Criar atalho em: 的本地化字符串。
    /// </summary>
    internal static string DragDropToolTip {
        get {
            return ResourceManager.GetString("DragDropToolTip", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Operação falhou.
    ///Certifique-se de que o arquivo ou o alvo do link exista:
    ///
    ///{0};Erro - QTTabBar;Aviso: Não foi possível ativar automaticamente o QTTabBar. Para habilitá-lo manualmente, pressione e solte a tecla Alt e selecione QTTabBar no menu Exibir/Barras de ferramentas.;Não foi possível ativar;Erro;Não é possível carregar a biblioteca hook do QTTabBar.;Não é possível inicializar a biblioteca hook do QTTabBar.;Alguns recursos podem não ser funcionais. Para resolver isso, você pode precisar reinstalar o  [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string ErrorDialogs {
        get {
            return ResourceManager.GetString("ErrorDialogs", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Arquivos de Imagem;Arquivos de Idioma;Arquivos de Plugin 的本地化字符串。
    /// </summary>
    internal static string FileFilters {
        get {
            return ResourceManager.GetString("FileFilters", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Caminho;Hash;Fechar;Limpar;Atualizar;Sempre visível;Mostrar resultados;Limpar ao sair;Caminho completo;(Calculando agora...) 的本地化字符串。
    /// </summary>
    internal static string FileHashComputer {
        get {
            return ResourceManager.GetString("FileHashComputer", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 pt_BR 的本地化字符串。
    /// </summary>
    internal static string Language {
        get {
            return ResourceManager.GetString("Language", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Todos;Esquerda;Superior;Direita;Inferior 的本地化字符串。
    /// </summary>
    internal static string MarginDropDown {
        get {
            return ResourceManager.GetString("MarginDropDown", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Pesquisa da Área de trabalho;O arquivo de imagem é inválido.
    ///
    ///Por favor, especifique arquivo de imagem 432 x 40 px.;Resultados da Pesquisa em;atalho;Escolha o arquivo;Escolha a pasta;Experimental;dummy 的本地化字符串。
    /// </summary>
    internal static string Misc_Strings {
        get {
            return ResourceManager.GetString("Misc_Strings", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Altera como o Explorer do Windows se comporta.;Modo de janela única;Capturar novas janelas do Explorer como novas abas;Não capturar novas janelas do Explorer;Local padrão para novas janelas e abas;Salvando sessão;Iniciar uma nova sessão a cada vez;Restaurar todas as abas da sessão anterior;Restaurar apenas as abas bloqueadas da sessão anterior;Quando o botão fechar é clicado;Fechar janela;Fechar aba atual;Fechar todas as abas desbloqueadas;Enviar janela para a bandeja de tarefas;Fechar;Minimizar;Botão azul  [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page01_Window {
        get {
            return ResourceManager.GetString("Options_Page01_Window", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Altera as opções relacionadas a abas.;Abrir novas abas:;Quando a aba atual é fechada, alterne para:;Alternar para novas abas imediatamente;Reutilizar as abas existentes;Renomear abas ambíguas;Ao arrastar, pairando sobre uma aba,;Alternar para essa;Mostrar menu de subpastas;Ícones da aba;Mostrar Ícones de pastas em abas;Mostrar menu de dica da subpasta quando o ícone é clicado;Mostrar a letra da unidade no ícone;Botão fechar;Mostrar botão fechar nas abas;Apenas com a tecla Alt pressionada;Apenas ao passar o  [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page02_Tabs {
        get {
            return ResourceManager.GetString("Options_Page02_Tabs", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Ativa ou desativa os ajustes da Visualização da Lista do Explorer.;Ajustes que podem ser usados ​​com a Visualização em Lista;Exibir cabeçalhos de coluna em todos os modos de visualização (Windows Vista/7);Usar visualização padrão do sistema de arquivos para pastas de Biblioteca (Windows 7);Desmarcar a extensão do arquivo ao renomear arquivos (Windows XP);Seleção de ciclo com F2 durante a renomeação;Enrole ao redor ao mover a seleção com as teclas de seta;Backspace sobe um nível (Windows Vista/7);Rolagem co [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page03_Tweaks {
        get {
            return ResourceManager.GetString("Options_Page03_Tweaks", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Altera o comportamento da ferramenta de menu de subpastas e pré-visualização.;Dicas de subpastas;Ativar dicas de subpasta;Apenas com a tecla Shift pressionada;Mostrar arquivos;Mostrar dicas de ferramentas ao passar mouse sobre itens;Visualizar dicas de ferramentas;Ativar visualizar de dicas;Apenas com a tecla Shift pressionada;Mostrar Informações do arquivo abaixo das imagens;Largura x altura máxima:;Fonte:;Tipos de arquivos de texto;Tipos de arquivos de imagem e vídeo 的本地化字符串。
    /// </summary>
    internal static string Options_Page04_Tooltips {
        get {
            return ResourceManager.GetString("Options_Page04_Tooltips", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Opções gerais para o comportamento do Qttabbar.;Integração da barra de tarefas;Mostrar visualizações de abas na Barra de tarefas;Histórico;Manter histórico de abas fechadas;Limpar;Manter histórico de arquivos abertos;Rede;Tempo limite de rede (Digite 0 para o padrão do sistema):;Verifique se há atualizações periodicamente;Verificar;Exportar;Exportar Configurações;Limpar histórico de arquivos?;Limpar histórico de abas? 的本地化字符串。
    /// </summary>
    internal static string Options_Page05_General {
        get {
            return ResourceManager.GetString("Options_Page05_General", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Altere a aparência das abas ou da barra de abas.;Imagem da aba;Imagem da aba personalizada:;Tamanho da margens:;Sobreposição da área:;Conteúdo da margens:;Acertar áreas transparentes de teste;Tamanho da aba;Altura:;Largura mín.:;Largura máx.:;Modo de tamanho:;Largura completa;Mesmo tamanho;Texto da aba;Cores do texto:;Cores de sombra:;Cor ativa;Cor inativa;Cor do realce;Fonte de texto:;Alinhamento:;Esquerda;Centro;Fundo da barra de ferramentas;Imagem;Cor sólida;Imagem para cada barra separada;Modo de estica [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page06_Appearance {
        get {
            return ResourceManager.GetString("Options_Page06_Appearance", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Atribui comandos a diferentes ações do mouse.;Para adicionar um vinculo do mouse, execute uma ação do mouse no ícone de adição à esquerda do tipo de destino apropriado. Para remover um vinculo, selecione-a na lista e pressione a tecla Delete.;Outras opções do mouse;Roda do mouse rola a janela sob o mouse;Acordar mouse;Ação;Em qualquer lugar;Aba;Histórico da barra de abas;Link de Pasta;Arquivo ou Pasta;Fundo do Explorer;Clique Direito;Clique direito;Clique do Meio;Duplo Clique;X1 Clique;X2 Clique;Este botão  [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page07_Mouse {
        get {
            return ResourceManager.GetString("Options_Page07_Mouse", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Altera os atalhos de teclado.;Selecione uma ação da lista e pressione o gesto de tecla que você gostaria de vincular a ela.  Pressione Escape para limpar a ligação.;Outras opções de teclado;Mostrar a janela do Alternador de Abas quando Ctrl + Tab é pressionado;Ação;Teclas;Esta tecla já está atribuída a:;Deveria ser reatribuído?;Conflito de teclas 的本地化字符串。
    /// </summary>
    internal static string Options_Page08_Keys {
        get {
            return ResourceManager.GetString("Options_Page08_Keys", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Cria e gerencia grupos de abas.;Para atribuir uma tecla de atalho a um grupo, selecione-o e pressione o gesto de tecla apropriada. Pressione Escape para limpar a ligação.;Criar novo grupo;Pasta;Inicialização;Tecla de atalho;Novo grupo;Abrir grupo &quot;{0}&quot; 的本地化字符串。
    /// </summary>
    internal static string Options_Page09_Groups {
        get {
            return ResourceManager.GetString("Options_Page09_Groups", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Cria atalhos para arquivos ou aplicativos comumente usados.;Para atribuir uma tecla de atalho a um aplicativo, selecione-o e pressione o gesto de tecla apropriado. Pressione Escape para limpar a ligação.;Criar Nova Pasta;Caminho:;Argumentos:;Diretório de Trabalho:;Aplicativo;Tecla de atalho;As seguintes palavras-chave são substituídas por strings de caminho duplo em tempo de execução.;Arquivos selecionados.;Pastas selecionadas.;Arquivos e pastas selecionados.;Pasta atual.;Pasta atual se não houver seleção,  [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string Options_Page10_Apps {
        get {
            return ResourceManager.GetString("Options_Page10_Apps", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Personaliza a barra de botão.;Botões;Opções da barra de botão;Ícones grandes;Mostrar rótulos dos botões;Bloquear ordem dos menus do botão suspenso;Bloqueie tamanho da caixa de pesquisa;Imagens de botão personalizadas 的本地化字符串。
    /// </summary>
    internal static string Options_Page11_ButtonBar {
        get {
            return ResourceManager.GetString("Options_Page11_ButtonBar", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Gerencia os plugins de terceiros.;Instalar plugin;(Desativado);por {0};{0} foi removido.;Este plugin será instalado quando você pressionar OK ou Aplicar.;Este plugin será ativado quando você pressionar OK ou Aplicar.;Este plugin será desativado quando você pressionar OK ou Aplicar.;Desinstalar este plug-in também desinstalará os seguintes plugins:;Proceder?;Ativar;Desativar 的本地化字符串。
    /// </summary>
    internal static string Options_Page12_Plugins {
        get {
            return ResourceManager.GetString("Options_Page12_Plugins", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Altera o idioma.;Idioma principal;Usar idioma integrado:;Usar arquivo de idioma:;Arquivos de idiomas de plugin;Editor de arquivos de idioma;Mostrar Editor de Idiomas...;Original;Traduzido;Redefinir todas as entradas ao seu valor original?;Erro ao salvar o arquivo.;Chinês simplificado;Inglês;Alemão 的本地化字符串。
    /// </summary>
    internal static string Options_Page13_Language {
        get {
            return ResourceManager.GetString("Options_Page13_Language", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Exibe as informações de créditos e da versão.;Código original por {0};Desenvolvedor Chefe:;Outros Desenvolvedores:;Ícones e gráficos:;Se você achou o Qttabbar útil, por favor considere fazer uma pequena doação.;汉化修改：;Criado por: {0} 的本地化字符串。
    /// </summary>
    internal static string Options_Page14_About {
        get {
            return ResourceManager.GetString("Options_Page14_About", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Opções do QTTabBar;Redefinir todas as opções nesta página para seus valores padrão?;Redefinir todas as opções para seus valores padrão? Isso não afetará grupos, aplicativos ou plugins.;Confirmações 的本地化字符串。
    /// </summary>
    internal static string OptionsDialog {
        get {
            return ResourceManager.GetString("OptionsDialog", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 https://github.com/indiff/qttabbar/blob/master/QTTabBar/Resources/wechat_pay.jpg 的本地化字符串。
    /// </summary>
    internal static string PayPalURL {
        get {
            return ResourceManager.GetString("PayPalURL", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Voltar;Avançar;Volte para início;Avançar para o fim;Selecionar próxima aba;Selecionar aba anterior;Selecionar primeira aba;Selecionar última aba;Alternar para a última aba ativada;Abrir nova aba;Abrir nova janela;Mesclar abas de outras janelas;Fechar aba atual;Fechar todas mais atual;Fechar esquerda;Fechar direita;Fechar janela;Desfazer perto;Clonar aba atual;Abrir pasta atual em uma nova janela;Bloquear / desbloquear atual;Bloquear / desbloquear todas;Procurar pasta;Criar novo grupo;Abrir diálogo de opção; [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string ShortcutKeys_ActionNames {
        get {
            return ResourceManager.GetString("ShortcutKeys_ActionNames", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 QTTabBar;{0} (Plugin) 的本地化字符串。
    /// </summary>
    internal static string ShortcutKeys_Groups {
        get {
            return ResourceManager.GetString("ShortcutKeys_Groups", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 https://github.com/indiff/qttabbar 的本地化字符串。
    /// </summary>
    internal static string SiteURL {
        get {
            return ResourceManager.GetString("SiteURL", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Fechar;Fechar a direita;Fechar esquerda;Fechar todas menos essa;Adicionar para o grupo;Criar novo grupo;Bloquear;Duplicar;Nova janela;Copiar caminho;Propriedades;Histórico de abas;Grupos;Desfazer fechado;Última ativada;Arquivos abertos recentes;Procurar pasta;Fechar todas mais atual;Fechar janela;Opções;Desbloquear;Adicionar ao menu de aplicativos : ;itens;Cancelar;Ramos;Remova este item do menu;A&amp;brir conteúdo da pasta;Rótulo da aba;Ordenar aba por;Nome;Caminho;Ativa;Bloqueie barras de ferramentas;Mesclar  [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string TabBar_Menu {
        get {
            return ResourceManager.GetString("TabBar_Menu", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 QTTabBar falhou ao abrir
    ///
    /// &quot;{0}&quot;. 的本地化字符串。
    /// </summary>
    internal static string TabBar_Message {
        get {
            return ResourceManager.GetString("TabBar_Message", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Criar um novo grupo;Nome do grupo:;Adicionar todas abas 的本地化字符串。
    /// </summary>
    internal static string TabBar_NewGroup {
        get {
            return ResourceManager.GetString("TabBar_NewGroup", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Janela;Abas;Ajustes;Dicas de ferramentas;Geral;Aparência;Mouse;Teclas;Grupos;Aplicativos;Barra de Botão;Plugins;Idioma;Sobre 的本地化字符串。
    /// </summary>
    internal static string TabBar_Option_Genre {
        get {
            return ResourceManager.GetString("TabBar_Option_Genre", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Barra de tarefas;Área de trabalho;Bloquear itens;Desenhar fundo do título;Menu de clique único;Ativar teclas de atalho de aplicativo 的本地化字符串。
    /// </summary>
    internal static string TaskBar_Menu {
        get {
            return ResourceManager.GetString("TaskBar_Menu", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Grupos;Desfazer fechado;Aplicativos;Arquivos abertos recente 的本地化字符串。
    /// </summary>
    internal static string TaskBar_Titles {
        get {
            return ResourceManager.GetString("TaskBar_Titles", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 1 janela;{0} janelas 的本地化字符串。
    /// </summary>
    internal static string TrayIcon {
        get {
            return ResourceManager.GetString("TrayIcon", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Uma nova versão do Qttabbar foi lançada:;Pressione OK para ir ao site.;Sua versão do QTTabBar está atualizada.;Nova versão de desenvolvimento encontrada:;Arquivo de versão não encontrado (404).;Erro de rede desconhecido.;Servidor não encontrado.;O servidor retornou as strings erradas. 的本地化字符串。
    /// </summary>
    internal static string UpdateCheck {
        get {
            return ResourceManager.GetString("UpdateCheck", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 DevBuild: 2022/8/15 19:01:42 (2.0.50727.9164) 的本地化字符串。
    /// </summary>
    internal static string Version_QTTabBar {
        get {
            return ResourceManager.GetString("Version_QTTabBar", resourceCulture);
        }
    }
}
