name: "CodeQL"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '22 1 * * 0'
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: windows-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: 'latest'

    - name: NuGet Restore
      run: nuget restore "QTTabBar Rebirth.sln"

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Build
      shell: pwsh
      run: |
        $slnDir = $env:GITHUB_WORKSPACE + "\"
        msbuild "QTTabBar\QTTabBar.csproj" /t:Build "/p:Configuration=Release" "/p:SolutionDir=$slnDir"

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
