[image]
# Only takes effect in random mode
random=false
# Image position
#0 = Left top
#1 = Right top
#2 = Left bottom
#3 = Right bottom
#4 = Center
#5 = Zoom
#6 = Zoom Fill
posType=3
# Image alpha
imgAlpha= 255
# If a custom file exists, load it; otherwise load images from the directory: *.png *.jpg *.jpeg C:\\ProgramData\\QTTabBar\\Image\\bgImage.png
imgPath=""